import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'ko' | 'en' | 'ja' | 'zh' | 'es';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    ko: {
        'dashboard.totalPatients': '전체 환자 수',
        'dashboard.activeAlerts': '현재 알람',
        'dashboard.criticalPatients': '위급 환자',
        'dashboard.devicesConnected': '연결된 장비',
        'dashboard.heartRateTitle': '심박수 (Heart Rate)',
        'dashboard.breathingRateTitle': '호흡수 (Breathing Rate)',
        'dashboard.sortedByUrgency': '긴급도 순 정렬',
        'dashboard.heartEmergency': '심박 위급',
        'dashboard.breathingEmergency': '호흡 위급',
        'dashboard.fallDetected': '낙상 감지',
        'dashboard.headerTitle': '의료 모니터링 대시보드',
        'dashboard.headerSubtitle': '환자 모니터링 시스템',
        'sidebar.dashboard': '통합 대시보드',
        'sidebar.patientList': '환자 목록',
        'sidebar.alertHistory': '알림 기록',
        'sidebar.sleepManagement': '수면 관리',
        'sidebar.registration': '환자 등록',
        'sidebar.militaryGps': '군사 GPS',
        'sidebar.settings': '설정',
        'sidebar.userName': '김민준 박사',
        'sidebar.role': '시스템 관리자',
        'header.systemOnline': '온라인',
        'header.systemOffline': '오프라인',
        'header.exportReport': '보고서 내보내기',
        'header.liveMonitor': '라이브 모니터',
        'alerts.title': '긴급 알림',
        'alerts.description': '과거 발생한 알림 내역을 확인하는 페이지입니다.',
        'alerts.patient': '환자',
        'alerts.value': '수치',
        'alerts.acknowledge': '확인',
        'alerts.resolve': '해결',
        'alerts.viewAll': '전체 보기',
        'table.patientId': '환자 ID',
        'table.heartRate': '심박수 (BPM)',
        'table.breathingRate': '호흡수 (RPM)',
        'table.sleepState': '수면 상태',
        'table.alertStatus': '알림 상태',
        'table.deviceStatus': '장비 상태',
        'table.lastUpdated': '최근 업데이트',
        'table.actions': '작업',
        'table.viewDetails': '상세 보기',
        'table.searchPlaceholder': 'ID 또는 이름으로 검색...',
        'table.showing': '표시 중',
        'table.to': '내용',
        'table.of': '중',
        'table.patients': '명의 환자',
        'table.filteredFrom': '필터링됨 (전체',
        'table.total': '명 중)',
        'table.previous': '이전',
        'table.next': '다음',
        'table.page': '페이지',
        'table.overview': '환자 개요',
        'table.realTime': '모든 환자의 실시간 모니터링',
        'table.bloodType': '혈액형',
        'status.critical': '위급',
        'status.warning': '경고',
        'status.caution': '주의',
        'status.normal': '정상',
        'status.stable': '안정',
        'status.online': '온라인',
        'status.offline': '오프라인',
        'status.error': '오류',
        'status.maintenance': '점검 중',
        'status.connected': '연결됨',
        'status.disconnected': '연결 끊김',
        'status.labelPrefix': '상태: ',
        'time.justNow': '방금 전',
        'time.secondsAgo': '초 전',
        'time.minutesAgo': '분 전',
        'time.hour': '시간',
        'time.minute': '분',
        'detail.back': '이전으로',
        'detail.patientInfo': '환자 정보',
        'detail.gender': '성별',
        'detail.age': '연령',
        'detail.room': '병실',
        'detail.admissionDate': '입원일',
        'detail.admissionStatus': '입원 일차',
        'detail.diagnosis': '진단명',
        'detail.doctor': '주치의',
        'detail.hr': '심박수',
        'detail.stress': '스트레스',
        'detail.rr': '호흡수',
        'detail.sleepEfficiency': '수면 효율',
        'detail.connection': '연결 상태',
        'detail.optimized': '최적화',
        'detail.sleepAnalysis': '수면 상세 분석',
        'detail.hrMonitoring': '심박수 모니터링',
        'detail.rrMonitoring': '호흡수 모니터링',
        'detail.detailedRecord': '환자 상세 기록',
        'detail.address': '주소',
        'detail.emergencyContact': '비상 연락처',
        'detail.allergies': '알레르기',
        'detail.clinicalFindings': '임상 소견',
        'detail.underlyingDisease': '기저 질환',
        'detail.medications': '복용 약물',
        'detail.diet': '식단',
        'detail.memo': '메모',
        'detail.alerts': '위험 알림',
        'detail.deepSleep': '깊은 수면',
        'detail.lightSleep': '얕은 수면',
        'detail.remSleep': 'REM 수면',
        'detail.awake': '깨어남',
        'detail.days': '일',
        'detail.yearsOld': '세',
        'detail.roomNumber': '호',
        'detail.observe': '관찰 필요',
        'detail.none': '없음',
        'detail.checkMedication': '처방 내역 확인 필요',
        'detail.generalDiet': '일반식 (병원식)',
        'detail.noSpecialMemo': '특이사항 없음',
        'gps.title': '군사 GPS',
        'gps.description': '군사 작전 구역 내 환자 위치 추적 페이지입니다.',
        'registration.title': '환자 정보 등록',
        'registration.description': '새로운 환자 또는 장비 정보를 등록하는 페이지입니다.',
        'registration.basicInfo': '기본 정보 (Basic Information)',
        'registration.patientName': '환자명',
        'registration.dob': '생년월일 (Date of Birth)',
        'registration.gender': '성별 (Gender)',
        'registration.select': '선택하세요',
        'registration.male': '남성',
        'registration.female': '여성',
        'registration.contact': '환자 연락처 (Patient Contact)',
        'registration.deviceInfo': '장치 정보 (Device Information)',
        'registration.deviceId': '장치 ID (Device ID)',
        'registration.sensorType': '센서 유형 (Sensor Type)',
        'registration.radar60ghz': '60GHz 레이더 (60GHz Radar)',
        'registration.careFacility': '관리 시설 (Care Facility)',
        'registration.facilityName': '시설명 (Facility Name)',
        'registration.registrationDate': '등록일 (Registration Date)',
        'registration.reset': '초기화',
        'registration.submit': '등록하기',
        'registration.success': '환자 정보가 등록되었습니다.',
        'sleep.title': '수면 관리',
        'sleep.description': '환자별 수면 패턴 및 품질 분석 페이지입니다.',
        'sleep.sessionSummary': '수면 요약',
        'sleep.lastNight': '지난 밤',
        'sleep.totalSleep': '총 수면 시간',
        'sleep.goal': '목표',
        'sleep.efficiency': '수면 효율',
        'sleep.interruptions': '깨어남 횟수',
        'sleep.latency': '입면 시간',
        'sleep.normalRange': '정상 범위',
        'sleep.timesWokenUp': '깨어난 횟수',
        'sleep.timeToFallAsleep': '잠들 때까지 걸린 시간',
        'sleep.stagesDistribution': '수면 단계 구성',
        'sleep.totalTimeInBed': '총 침대 체류 시간',
        'sleep.overallSleepScore': '종합 수면 점수',
        'sleep.excellent': '우수',
        'sleep.fair': '보통',
        'sleep.poor': '저조',
        'sleep.avgComparedToUsers': '동일 연령대 평균 대비 수치입니다.',
        'sleep.hypnogram': '수면 단계 그래프',
        'sleep.timeInfo': '수면 시간 정보',
        'sleep.bedIn': '취침 준비',
        'sleep.sleep': '수면 시작',
        'sleep.wakeUp': '기상 시간',
        'sleep.bedOut': '침대 이탈',
        'sleep.trend': '수면 트렌드',
        'sleep.day': '일별',
        'sleep.weekly': '주간',
        'sleep.monthly': '월간',
        'sleep.vitalsCorrelation': '활력 징후 상관관계',
        'sleep.avgHr': '평균 심박수',
        'sleep.avgResp': '평균 호흡수',
        'sleep.avgSpO2': '평균 산소포화도',
        'settings.title': '설정',
        'settings.subtitle': '시스템 환경 설정',
        'settings.language': '언어 설정',
        'settings.selectLanguage': '언어 선택',
        'settings.description': '시스템 환경 설정을 변경하는 페이지입니다.',
        'settings.dataManagement': '데이터 관리',
        'settings.dataRetention': '데이터 보관 기간 (일)',
        'settings.autoBackup': '자동 백업 활성',
        'settings.langUpdateNote': '언어를 변경하면 전체 앱의 인터페이스가 선택한 언어로 변경됩니다.',
        'common.save': '저장',
        'common.cancel': '취소',
        'common.bpm': 'BPM',
        'common.rpm': 'RPM',
        'error.loadingData': '데이터를 불러오는 중 오류가 발생했습니다.',
        'error.patientNotFound': '환자 정보를 찾을 수 없습니다.',
    },
    en: {
        'dashboard.totalPatients': 'Total Patients',
        'dashboard.activeAlerts': 'Active Alerts',
        'dashboard.criticalPatients': 'Critical Patients',
        'dashboard.devicesConnected': 'Devices Connected',
        'dashboard.heartRateTitle': 'Heart Rate',
        'dashboard.breathingRateTitle': 'Breathing Rate',
        'dashboard.sortedByUrgency': 'Sorted by Urgency',
        'dashboard.heartEmergency': 'Heart Emergency',
        'dashboard.breathingEmergency': 'Breathing Emergency',
        'dashboard.fallDetected': 'Fall Detected',
        'dashboard.headerTitle': 'Medical Monitoring Dashboard',
        'dashboard.headerSubtitle': 'Patient Monitoring System',
        'sidebar.dashboard': 'Dashboard',
        'sidebar.patientList': 'Patient List',
        'sidebar.alertHistory': 'Alert History',
        'sidebar.sleepManagement': 'Sleep Management',
        'sidebar.registration': 'Patient Registration',
        'sidebar.militaryGps': 'Military GPS',
        'sidebar.settings': 'Settings',
        'sidebar.userName': 'Dr. Kim Min-jun',
        'sidebar.role': 'System Administrator',
        'header.systemOnline': 'Online',
        'header.systemOffline': 'Offline',
        'header.exportReport': 'Export Report',
        'header.liveMonitor': 'Live Monitor',
        'alerts.title': 'Emergency Alerts',
        'alerts.description': 'View history of past alerts and notifications.',
        'alerts.patient': 'Patient',
        'alerts.value': 'Value',
        'alerts.acknowledge': 'Acknowledge',
        'alerts.resolve': 'Resolve',
        'alerts.viewAll': 'View All',
        'table.patientId': 'Patient ID',
        'table.heartRate': 'Heart Rate (BPM)',
        'table.breathingRate': 'Breathing Rate (RPM)',
        'table.sleepState': 'Sleep State',
        'table.alertStatus': 'Alert Status',
        'table.deviceStatus': 'Device Status',
        'table.lastUpdated': 'Last Updated',
        'table.actions': 'Actions',
        'table.viewDetails': 'View Details',
        'table.searchPlaceholder': 'Search by ID or Name...',
        'table.showing': 'Showing',
        'table.to': 'to',
        'table.of': 'of',
        'table.patients': 'patients',
        'table.filteredFrom': 'filtered from',
        'table.total': 'total)',
        'table.previous': 'Previous',
        'table.next': 'Next',
        'table.page': 'Page',
        'table.overview': 'Patient Overview',
        'table.realTime': 'Real-time monitoring of all patients',
        'table.bloodType': 'Blood Type',
        'status.critical': 'Critical',
        'status.warning': 'Warning',
        'status.caution': 'Caution',
        'status.normal': 'Normal',
        'status.stable': 'Stable',
        'status.online': 'Online',
        'status.offline': 'Offline',
        'status.error': 'Error',
        'status.maintenance': 'Maintenance',
        'status.connected': 'Connected',
        'status.disconnected': 'Disconnected',
        'status.labelPrefix': 'Status: ',
        'time.justNow': 'Just now',
        'time.secondsAgo': 's ago',
        'time.minutesAgo': 'm ago',
        'time.hour': 'h',
        'time.minute': 'm',
        'detail.back': 'Back',
        'detail.patientInfo': 'Patient Info',
        'detail.gender': 'Gender',
        'detail.age': 'Age',
        'detail.room': 'Room',
        'detail.admissionDate': 'Admission Date',
        'detail.admissionStatus': 'Admission Day',
        'detail.diagnosis': 'Diagnosis',
        'detail.doctor': 'Doctor',
        'detail.hr': 'Heart Rate',
        'detail.stress': 'Stress Index',
        'detail.rr': 'Breathing Rate',
        'detail.sleepEfficiency': 'Sleep Efficiency',
        'detail.connection': 'Connection Status',
        'detail.optimized': 'Optimized',
        'detail.sleepAnalysis': 'Sleep Record Analysis',
        'detail.hrMonitoring': 'Heart Rate Monitoring',
        'detail.rrMonitoring': 'Breathing Rate Monitoring',
        'detail.detailedRecord': 'Detailed Record',
        'detail.address': 'Address',
        'detail.emergencyContact': 'Emergency Contact',
        'detail.allergies': 'Allergies',
        'detail.clinicalFindings': 'Clinical Findings',
        'detail.underlyingDisease': 'Underlying Disease',
        'detail.medications': 'Medications',
        'detail.diet': 'Diet',
        'detail.memo': 'Memo',
        'detail.alerts': 'Emergency Alerts',
        'detail.deepSleep': 'Deep Sleep',
        'detail.lightSleep': 'Light Sleep',
        'detail.remSleep': 'REM Sleep',
        'detail.awake': 'Awake',
        'detail.days': 'days',
        'detail.yearsOld': 'yo',
        'detail.roomNumber': '',
        'detail.observe': 'Needs Observation',
        'detail.none': 'None',
        'detail.checkMedication': 'Contact Pharmacy',
        'detail.generalDiet': 'General Diet',
        'detail.noSpecialMemo': 'No special notes',
        'gps.title': 'Military GPS',
        'gps.description': 'Patient location tracking in military operation area.',
        'registration.title': 'Patient Registration',
        'registration.description': 'Register new patient or equipment information.',
        'registration.basicInfo': 'Basic Information',
        'registration.patientName': 'Patient Name',
        'registration.dob': 'Date of Birth',
        'registration.gender': 'Gender',
        'registration.select': 'Select...',
        'registration.male': 'Male',
        'registration.female': 'Female',
        'registration.contact': 'Patient Contact',
        'registration.deviceInfo': 'Device Information',
        'registration.deviceId': 'Device ID',
        'registration.sensorType': 'Sensor Type',
        'registration.radar60ghz': '60GHz Radar',
        'registration.careFacility': 'Care Facility',
        'registration.facilityName': 'Facility Name',
        'registration.registrationDate': 'Registration Date',
        'registration.reset': 'Reset',
        'registration.submit': 'Register Patient',
        'registration.success': 'Patient info registered.',
        'sleep.title': 'Sleep Management',
        'sleep.description': 'Analyze sleep patterns and quality per patient.',
        'sleep.sessionSummary': 'Sleep Session Summary',
        'sleep.lastNight': 'Last Night',
        'sleep.totalSleep': 'TOTAL SLEEP',
        'sleep.goal': 'Goal',
        'sleep.efficiency': 'EFFICIENCY',
        'sleep.interruptions': 'INTERRUPTIONS',
        'sleep.latency': 'LATENCY',
        'sleep.normalRange': 'Normal Range',
        'sleep.timesWokenUp': 'Times woken up',
        'sleep.timeToFallAsleep': 'Time to fall asleep',
        'sleep.stagesDistribution': 'Sleep Stages Distribution',
        'sleep.totalTimeInBed': 'Total time in bed',
        'sleep.overallSleepScore': 'Overall Sleep Score',
        'sleep.excellent': 'Excellent',
        'sleep.fair': 'Fair',
        'sleep.poor': 'Poor',
        'sleep.avgComparedToUsers': 'Average compared to users in this age group.',
        'sleep.hypnogram': 'Sleep Hypnogram',
        'sleep.timeInfo': 'Sleep Time Info',
        'sleep.bedIn': 'Bed in',
        'sleep.sleep': 'Sleep',
        'sleep.wakeUp': 'Wake up',
        'sleep.bedOut': 'Bed out',
        'sleep.trend': 'Sleep Trend',
        'sleep.day': 'Day',
        'sleep.weekly': 'Weekly',
        'sleep.monthly': 'Monthly',
        'sleep.vitalsCorrelation': 'Vitals Correlation',
        'sleep.avgHr': 'Avg HR',
        'sleep.avgResp': 'Avg Resp',
        'sleep.avgSpO2': 'Avg SpO2',
        'settings.title': 'Settings',
        'settings.subtitle': 'System Preferences',
        'settings.language': 'Language',
        'settings.selectLanguage': 'Select language',
        'settings.description': 'Configure system environment settings.',
        'settings.dataManagement': 'Data Management',
        'settings.dataRetention': 'Data Retention (Days)',
        'settings.autoBackup': 'Auto Backup',
        'settings.langUpdateNote': 'Changing the language will update the entire app interface to the selected language.',
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.bpm': 'BPM',
        'common.rpm': 'RPM',
        'error.loadingData': 'An error occurred while loading data.',
        'error.patientNotFound': 'Patient information not found.',
    },
    ja: {
        'dashboard.totalPatients': '全患者数',
        'dashboard.activeAlerts': '現在のアラート',
        'dashboard.criticalPatients': '危篤患者',
        'dashboard.devicesConnected': '接続デバイス',
        'dashboard.heartRateTitle': '心拍数 (Heart Rate)',
        'dashboard.breathingRateTitle': '呼吸数 (Breathing Rate)',
        'dashboard.sortedByUrgency': '緊急度順',
        'dashboard.heartEmergency': '心拍緊急',
        'dashboard.breathingEmergency': '呼吸緊急',
        'dashboard.fallDetected': '転倒検知',
        'dashboard.headerTitle': '医療モニタリングダッシュボード',
        'dashboard.headerSubtitle': '患者監視システム',
        'sidebar.dashboard': '統合ダッシュボード',
        'sidebar.patientList': '患者リスト',
        'sidebar.alertHistory': '通知履歴',
        'sidebar.sleepManagement': '睡眠管理',
        'sidebar.registration': '患者登録',
        'sidebar.militaryGps': '軍事GPS',
        'sidebar.settings': '設定',
        'sidebar.userName': '金民俊 博士',
        'sidebar.role': 'システム管理者',
        'header.systemOnline': 'オンライン',
        'header.systemOffline': 'オフライン',
        'header.exportReport': 'レポート出力',
        'header.liveMonitor': 'ライブモニター',
        'alerts.title': '緊急通知',
        'alerts.description': '過去の通知履歴を確認するページです。',
        'alerts.patient': '患者',
        'alerts.value': '数値',
        'alerts.acknowledge': '確認',
        'alerts.resolve': '解決',
        'alerts.viewAll': 'すべて表示',
        'table.patientId': '患者ID',
        'table.heartRate': '心拍数 (BPM)',
        'table.breathingRate': '呼吸数 (RPM)',
        'table.sleepState': '睡眠状態',
        'table.alertStatus': '通知状態',
        'table.deviceStatus': 'デバイス状態',
        'table.lastUpdated': '最終更新',
        'table.actions': '操作',
        'table.viewDetails': '詳細表示',
        'table.searchPlaceholder': 'IDまたは名前で検索...',
        'table.showing': '表示中',
        'table.to': '〜',
        'table.of': '/',
        'table.patients': '人の患者',
        'table.filteredFrom': 'フィルタリング済み (全',
        'table.total': '人中)',
        'table.previous': '前へ',
        'table.next': '次へ',
        'table.page': 'ページ',
        'table.overview': '患者概要',
        'table.realTime': '全患者のリアルタイム監視',
        'table.bloodType': '血液型',
        'status.critical': '危篤',
        'status.warning': '警告',
        'status.caution': '注意',
        'status.normal': '正常',
        'status.stable': '安定',
        'status.online': 'オンライン',
        'status.offline': 'オフライン',
        'status.error': 'エラー',
        'status.maintenance': 'メンテナンス中',
        'status.connected': '接続済み',
        'status.disconnected': '切断',
        'status.labelPrefix': '状態: ',
        'time.justNow': '今',
        'time.secondsAgo': '秒前',
        'time.minutesAgo': '分前',
        'time.hour': '時間',
        'time.minute': '分',
        'detail.back': '戻る',
        'detail.patientInfo': '患者情報',
        'detail.gender': '性別',
        'detail.age': '年齢',
        'detail.room': '病室',
        'detail.admissionDate': '入院日',
        'detail.admissionStatus': '入院日数',
        'detail.diagnosis': '診断名',
        'detail.doctor': '主治医',
        'detail.hr': '心拍数',
        'detail.stress': 'ストレス',
        'detail.rr': '呼吸数',
        'detail.sleepEfficiency': '睡眠効率',
        'detail.connection': '接続状態',
        'detail.optimized': '最適化',
        'detail.sleepAnalysis': '睡眠詳細分析',
        'detail.hrMonitoring': '心拍数モニタリング',
        'detail.rrMonitoring': '呼吸数モニタリング',
        'detail.detailedRecord': '患者詳細記録',
        'detail.address': '住所',
        'detail.emergencyContact': '緊急連絡先',
        'detail.allergies': 'アレルギー',
        'detail.clinicalFindings': '臨床所見',
        'detail.underlyingDisease': '基礎疾患',
        'detail.medications': '服用薬',
        'detail.diet': '食事',
        'detail.memo': 'メモ',
        'detail.alerts': '危険通知',
        'detail.deepSleep': '深い睡眠',
        'detail.lightSleep': '浅い睡眠',
        'detail.remSleep': 'レム睡眠',
        'detail.awake': '覚醒',
        'detail.days': '日',
        'detail.yearsOld': '歳',
        'detail.roomNumber': '号',
        'detail.observe': '観察必要',
        'detail.none': 'なし',
        'detail.checkMedication': '処方内容の確認が必要',
        'detail.generalDiet': '一般食',
        'detail.noSpecialMemo': '特記事項なし',
        'gps.title': '軍事GPS',
        'gps.description': '作戦区域内の患者位置追跡ページです。',
        'registration.title': '患者情報の登録',
        'registration.description': '新しい患者またはデバイス情報の登録ページです。',
        'registration.basicInfo': '基本情報 (Basic Information)',
        'registration.patientName': '患者名',
        'registration.dob': '生年月日 (Date of Birth)',
        'registration.gender': '性別 (Gender)',
        'registration.select': '選択してください',
        'registration.male': '男性',
        'registration.female': '女性',
        'registration.contact': '患者連絡先 (Patient Contact)',
        'registration.deviceInfo': 'デバイス情報 (Device Information)',
        'registration.deviceId': 'デバイスID (Device ID)',
        'registration.sensorType': 'センサータイプ (Sensor Type)',
        'registration.radar60ghz': '60GHzレーダー (60GHz Radar)',
        'registration.careFacility': '管理施設 (Care Facility)',
        'registration.facilityName': '施設名 (Facility Name)',
        'registration.registrationDate': '登録日 (Registration Date)',
        'registration.reset': '初期化',
        'registration.submit': '登録する',
        'registration.success': '患者情報が登録されました。',
        'sleep.title': '睡眠管理',
        'sleep.description': '患者別睡眠パターンおよび品質分析ページです。',
        'sleep.sessionSummary': '睡眠サマリー',
        'sleep.lastNight': '昨夜',
        'sleep.totalSleep': '総睡眠時間',
        'sleep.goal': '目標',
        'sleep.efficiency': '睡眠効率',
        'sleep.interruptions': '中途覚醒',
        'sleep.latency': '入眠潜時',
        'sleep.normalRange': '正常範囲',
        'sleep.timesWokenUp': '覚醒回数',
        'sleep.timeToFallAsleep': '入眠時間',
        'sleep.stagesDistribution': '睡眠段階構成',
        'sleep.totalTimeInBed': '総就床時間',
        'sleep.overallSleepScore': '総合睡眠スコア',
        'sleep.excellent': '非常に良い',
        'sleep.fair': '普通',
        'sleep.poor': '低い',
        'sleep.avgComparedToUsers': '同年齢層の平均との比較値です。',
        'sleep.hypnogram': '睡眠段階グラフ',
        'sleep.timeInfo': '睡眠時間情報',
        'sleep.bedIn': '就床',
        'sleep.sleep': '入眠',
        'sleep.wakeUp': '起床',
        'sleep.bedOut': '離床',
        'sleep.trend': '睡眠トレンド',
        'sleep.day': '日別',
        'sleep.weekly': '週間',
        'sleep.monthly': '月間',
        'sleep.vitalsCorrelation': 'バイタルサイン相関',
        'sleep.avgHr': '平均心拍数',
        'sleep.avgResp': '平均呼吸数',
        'sleep.avgSpO2': '平均SpO2',
        'settings.title': '設定',
        'settings.subtitle': 'システム設定',
        'settings.language': '言語設定',
        'settings.selectLanguage': '言語を選択',
        'settings.description': 'システム環境設定を変更するページです。',
        'settings.dataManagement': 'データ管理',
        'settings.dataRetention': 'データ保存期間 (日)',
        'settings.autoBackup': '自動バックアップ有効',
        'settings.langUpdateNote': '言語を変更すると、アプリ全体のインターフェースが選択した言語に変更されます。',
        'common.save': '保存',
        'common.cancel': 'キャンセル',
        'common.bpm': 'BPM',
        'common.rpm': 'RPM',
        'error.loadingData': 'データの読み込み中にエラーが発生しました。',
        'error.patientNotFound': '患者情報が見つかりません。',
    },
    zh: {
        'dashboard.totalPatients': '患者总数',
        'dashboard.activeAlerts': '当前警报',
        'dashboard.criticalPatients': '危重患者',
        'dashboard.devicesConnected': '已连接设备',
        'dashboard.heartRateTitle': '心率 (Heart Rate)',
        'dashboard.breathingRateTitle': '呼吸率 (Breathing Rate)',
        'dashboard.sortedByUrgency': '按紧急度排序',
        'dashboard.heartEmergency': '心率紧急',
        'dashboard.breathingEmergency': '呼吸紧急',
        'dashboard.fallDetected': '跌倒检测',
        'dashboard.headerTitle': '医疗监控仪表板',
        'dashboard.headerSubtitle': '患者监控系统',
        'sidebar.dashboard': '综合仪表板',
        'sidebar.patientList': '患者列表',
        'sidebar.alertHistory': '警报记录',
        'sidebar.sleepManagement': '睡眠管理',
        'sidebar.registration': '患者注册',
        'sidebar.militaryGps': '军事GPS',
        'sidebar.settings': '设置',
        'sidebar.userName': '金民俊 博士',
        'sidebar.role': '系统管理员',
        'header.systemOnline': '在线',
        'header.systemOffline': '离线',
        'header.exportReport': '导出报告',
        'header.liveMonitor': '实时监控',
        'alerts.title': '紧急通知',
        'alerts.description': '查看过去警报记录的页面。',
        'alerts.patient': '患者',
        'alerts.value': '数值',
        'alerts.acknowledge': '确认',
        'alerts.resolve': '解决',
        'alerts.viewAll': '查看全部',
        'table.patientId': '患者ID',
        'table.heartRate': '心率 (BPM)',
        'table.breathingRate': '呼吸率 (RPM)',
        'table.sleepState': '睡眠状态',
        'table.alertStatus': '警报状态',
        'table.deviceStatus': '设备状态',
        'table.lastUpdated': '最后更新',
        'table.actions': '操作',
        'table.viewDetails': '查看详情',
        'table.searchPlaceholder': '通过ID或姓名搜索...',
        'table.showing': '显示',
        'table.to': '到',
        'table.of': '/',
        'table.patients': '名患者',
        'table.filteredFrom': '已过滤 (总共',
        'table.total': '名中的)',
        'table.previous': '上一页',
        'table.next': '下一页',
        'table.page': '页',
        'table.overview': '患者概览',
        'table.realTime': '所有患者的实时监控',
        'table.bloodType': '血型',
        'status.critical': '危重',
        'status.warning': '警告',
        'status.caution': '注意',
        'status.normal': '正常',
        'status.stable': '稳定',
        'status.online': '在线',
        'status.offline': '离线',
        'status.error': '错误',
        'status.maintenance': '维护中',
        'status.connected': '已连接',
        'status.disconnected': '已断开',
        'status.labelPrefix': '状态: ',
        'time.justNow': '刚刚',
        'time.secondsAgo': '秒前',
        'time.minutesAgo': '分钟前',
        'time.hour': '小时',
        'time.minute': '分钟',
        'detail.back': '返回',
        'detail.patientInfo': '患者信息',
        'detail.gender': '性别',
        'detail.age': '年龄',
        'detail.room': '病房',
        'detail.admissionDate': '入院日期',
        'detail.admissionStatus': '入院天数',
        'detail.diagnosis': '诊断',
        'detail.doctor': '主治医生',
        'detail.hr': '心率',
        'detail.stress': '压力指数',
        'detail.rr': '呼吸率',
        'detail.sleepEfficiency': '睡眠效率',
        'detail.connection': '连接状态',
        'detail.optimized': '已优化',
        'detail.sleepAnalysis': '睡眠详细分析',
        'detail.hrMonitoring': '心率监控',
        'detail.rrMonitoring': '呼吸率监控',
        'detail.detailedRecord': '患者详细记录',
        'detail.address': '地址',
        'detail.emergencyContact': '紧急联系人',
        'detail.allergies': '过敏',
        'detail.clinicalFindings': '临床发现',
        'detail.underlyingDisease': '基础疾病',
        'detail.medications': '服用药物',
        'detail.diet': '饮食',
        'detail.memo': '备注',
        'detail.alerts': '危险通知',
        'detail.deepSleep': '深度睡眠',
        'detail.lightSleep': '浅度睡眠',
        'detail.remSleep': '快动眼睡眠',
        'detail.awake': '醒来',
        'detail.days': '天',
        'detail.yearsOld': '岁',
        'detail.roomNumber': '号',
        'detail.observe': '需要观察',
        'detail.none': '无',
        'detail.checkMedication': '需要确认处方',
        'detail.generalDiet': '普通饮食',
        'detail.noSpecialMemo': '无特殊备注',
        'gps.title': '军事GPS',
        'gps.description': '在军事行动区域内的患者位置追踪页面。',
        'registration.title': '患者信息注册',
        'registration.description': '注册新患者或设备信息的页面。',
        'registration.basicInfo': '基本信息 (Basic Information)',
        'registration.patientName': '患者姓名',
        'registration.dob': '出生日期 (Date of Birth)',
        'registration.gender': '性别 (Gender)',
        'registration.select': '请选择',
        'registration.male': '男性',
        'registration.female': '女性',
        'registration.contact': '患者联系方式 (Patient Contact)',
        'registration.deviceInfo': '设备信息 (Device Information)',
        'registration.deviceId': '设备ID (Device ID)',
        'registration.sensorType': '传感器类型 (Sensor Type)',
        'registration.radar60ghz': '60GHz雷达 (60GHz Radar)',
        'registration.careFacility': '管理设施 (Care Facility)',
        'registration.facilityName': '设施名称 (Facility Name)',
        'registration.registrationDate': '注册日期 (Registration Date)',
        'registration.reset': '重置',
        'registration.submit': '注册',
        'registration.success': '患者信息已注册。',
        'sleep.title': '睡眠管理',
        'sleep.description': '按患者分析睡眠模式和质量的页面。',
        'sleep.sessionSummary': '睡眠摘要',
        'sleep.lastNight': '昨晚',
        'sleep.totalSleep': '总睡眠时间',
        'sleep.goal': '目标',
        'sleep.efficiency': '睡眠效率',
        'sleep.interruptions': '醒来次数',
        'sleep.latency': '入睡潜伏期',
        'sleep.normalRange': '正常范围',
        'sleep.timesWokenUp': '醒来次数',
        'sleep.timeToFallAsleep': '入睡所需时间',
        'sleep.stagesDistribution': '睡眠阶段分布',
        'sleep.totalTimeInBed': '总在床时间',
        'sleep.overallSleepScore': '综合睡眠评分',
        'sleep.excellent': '优秀',
        'sleep.fair': '一般',
        'sleep.poor': '较差',
        'sleep.avgComparedToUsers': '与同年龄段平均水平的对比值。',
        'sleep.hypnogram': '睡眠阶段图表',
        'sleep.timeInfo': '睡眠时间信息',
        'sleep.bedIn': '上床',
        'sleep.sleep': '入睡',
        'sleep.wakeUp': '醒来',
        'sleep.bedOut': '起床',
        'sleep.trend': '睡眠趋势',
        'sleep.day': '每日',
        'sleep.weekly': '每周',
        'sleep.monthly': '每月',
        'sleep.vitalsCorrelation': '生命体征相关性',
        'sleep.avgHr': '平均心率',
        'sleep.avgResp': '平均呼吸率',
        'sleep.avgSpO2': '平均血氧饱和度',
        'settings.title': '设置',
        'settings.subtitle': '系统偏好设置',
        'settings.language': '语言设置',
        'settings.selectLanguage': '选择语言',
        'settings.description': '配置系统环境设置的页面。',
        'settings.dataManagement': '数据管理',
        'settings.dataRetention': '数据保留天数 (天)',
        'settings.autoBackup': '启用自动备份',
        'settings.langUpdateNote': '更改语言将把整个应用程序界面更新为所选语言。',
        'common.save': '保存',
        'common.cancel': '取消',
        'common.bpm': 'BPM',
        'common.rpm': 'RPM',
        'error.loadingData': '加载数据时出错。',
        'error.patientNotFound': '找不到患者信息。',
    },
    es: {
        'dashboard.totalPatients': 'Total de Pacientes',
        'dashboard.activeAlerts': 'Alertas Activas',
        'dashboard.criticalPatients': 'Pacientes Críticos',
        'dashboard.devicesConnected': 'Dispositivos Conectados',
        'dashboard.heartRateTitle': 'Frecuencia Cardíaca (Heart Rate)',
        'dashboard.breathingRateTitle': 'Frecuencia Respiratoria (Breathing Rate)',
        'dashboard.sortedByUrgency': 'Ordenado por Urgencia',
        'dashboard.heartEmergency': 'Emergencia Cardíaca',
        'dashboard.breathingEmergency': 'Emergencia Respiratoria',
        'dashboard.fallDetected': 'Caída Detectada',
        'dashboard.headerTitle': 'Panel de Monitoreo Médico',
        'dashboard.headerSubtitle': 'Sistema de Monitoreo de Pacientes',
        'sidebar.dashboard': 'Panel Principal',
        'sidebar.patientList': 'Lista de Pacientes',
        'sidebar.alertHistory': 'Historial de Alertas',
        'sidebar.sleepManagement': 'Gestión de Sueño',
        'sidebar.registration': 'Registro de Pacientes',
        'sidebar.militaryGps': 'GPS Militar',
        'sidebar.settings': 'Configuración',
        'sidebar.userName': 'Dr. Kim Min-jun',
        'sidebar.role': 'Administrador del Sistema',
        'header.systemOnline': 'En línea',
        'header.systemOffline': 'Desconectado',
        'header.exportReport': 'Exportar Informe',
        'header.liveMonitor': 'Monitor en Vivo',
        'alerts.title': 'Alertas de Emergencia',
        'alerts.description': 'Página para ver el historial de alertas pasadas.',
        'alerts.patient': 'Paciente',
        'alerts.value': 'Valor',
        'alerts.acknowledge': 'Reconocer',
        'alerts.resolve': 'Resolver',
        'alerts.viewAll': 'Ver Todo',
        'table.patientId': 'ID Paciente',
        'table.heartRate': 'Frec. Cardíaca (BPM)',
        'table.breathingRate': 'Frec. Respiratoria (RPM)',
        'table.sleepState': 'Estado de Sueño',
        'table.alertStatus': 'Estado de Alerta',
        'table.deviceStatus': 'Estado de Dispositivo',
        'table.lastUpdated': 'Última Actualización',
        'table.actions': 'Acciones',
        'table.viewDetails': 'Ver Detalles',
        'table.searchPlaceholder': 'Buscar por ID o Nombre...',
        'table.showing': 'Mostrando',
        'table.to': 'a',
        'table.of': 'de',
        'table.patients': 'pacientes',
        'table.filteredFrom': 'filtrado de un total de',
        'table.total': ')',
        'table.previous': 'Anterior',
        'table.next': 'Siguiente',
        'table.page': 'Página',
        'table.overview': 'Resumen del Paciente',
        'table.realTime': 'Monitoreo en tiempo real de todos los pacientes',
        'table.bloodType': 'Grupo Sanguíneo',
        'status.critical': 'Crítico',
        'status.warning': 'Advertencia',
        'status.caution': 'Precaución',
        'status.normal': 'Normal',
        'status.stable': 'Estable',
        'status.online': 'En línea',
        'status.offline': 'Desconectado',
        'status.error': 'Error',
        'status.maintenance': 'Mantenimiento',
        'status.connected': 'Conectado',
        'status.disconnected': 'Desconectado',
        'status.labelPrefix': 'Estado: ',
        'time.justNow': 'Recién',
        'time.secondsAgo': 's atrás',
        'time.minutesAgo': 'm atrás',
        'time.hour': 'h',
        'time.minute': 'm',
        'detail.back': 'Volver',
        'detail.patientInfo': 'Información del Paciente',
        'detail.gender': 'Género',
        'detail.age': 'Edad',
        'detail.room': 'Habitación',
        'detail.admissionDate': 'Fecha de Ingreso',
        'detail.admissionStatus': 'Días de Ingreso',
        'detail.diagnosis': 'Diagnóstico',
        'detail.doctor': 'Médico',
        'detail.hr': 'Frecuencia Cardíaca',
        'detail.stress': 'Índice de Estrés',
        'detail.rr': 'Frecuencia Respiratoria',
        'detail.sleepEfficiency': 'Eficiencia del Sueño',
        'detail.connection': 'Estado de Conexión',
        'detail.optimized': 'Optimizado',
        'detail.sleepAnalysis': 'Análisis de Sueño',
        'detail.hrMonitoring': 'Monitoreo de Frecuencia Cardíaca',
        'detail.rrMonitoring': 'Monitoreo de Frecuencia Respiratoria',
        'detail.detailedRecord': 'Registro Detallado',
        'detail.address': 'Dirección',
        'detail.emergencyContact': 'Contacto de Emergencia',
        'detail.allergies': 'Alergias',
        'detail.clinicalFindings': 'Hallazgos Clínicos',
        'detail.underlyingDisease': 'Enfermedad Subyacente',
        'detail.medications': 'Medicamentos',
        'detail.diet': 'Dieta',
        'detail.memo': 'Memo',
        'detail.alerts': 'Alertas de Riesgo',
        'detail.deepSleep': 'Sueño Profundo',
        'detail.lightSleep': 'Sueño Ligero',
        'detail.remSleep': 'Sueño REM',
        'detail.awake': 'Despierto',
        'detail.days': 'días',
        'detail.yearsOld': 'años',
        'detail.roomNumber': '',
        'detail.observe': 'Necesita Observación',
        'detail.none': 'Ninguno',
        'detail.checkMedication': 'Revisar prescripción',
        'detail.generalDiet': 'Dieta General',
        'detail.noSpecialMemo': 'Sin notas especiales',
        'gps.title': 'GPS Militar',
        'gps.description': 'Seguimiento de ubicación de pacientes en zona de operaciones.',
        'registration.title': 'Registro de Información del Paciente',
        'registration.description': 'Página para registrar nuevos pacientes o equipos.',
        'registration.basicInfo': 'Información Básica (Basic Information)',
        'registration.patientName': 'Nombre del Paciente',
        'registration.dob': 'Fecha de Nacimiento (Date of Birth)',
        'registration.gender': 'Género (Gender)',
        'registration.select': 'Seleccione...',
        'registration.male': 'Masculino',
        'registration.female': 'Femenino',
        'registration.contact': 'Contacto del Paciente (Patient Contact)',
        'registration.deviceInfo': 'Información del Dispositivo (Device Information)',
        'registration.deviceId': 'ID del Dispositivo (Device ID)',
        'registration.sensorType': 'Tipo de Sensor (Sensor Type)',
        'registration.radar60ghz': 'Radar 60GHz (60GHz Radar)',
        'registration.careFacility': 'Instalación de Cuidado (Care Facility)',
        'registration.facilityName': 'Nombre de la Instalación (Facility Name)',
        'registration.registrationDate': 'Fecha de Registro (Registration Date)',
        'registration.reset': 'Reiniciar',
        'registration.submit': 'Registrar',
        'registration.success': 'Información del paciente registrada.',
        'sleep.title': 'Gestión del Sueño',
        'sleep.description': 'Análisis de patrones y calidad del sueño.',
        'sleep.sessionSummary': 'Resumen de Sueño',
        'sleep.lastNight': 'Anoche',
        'sleep.totalSleep': 'SUEÑO TOTAL',
        'sleep.goal': 'Meta',
        'sleep.efficiency': 'EFICIENCIA',
        'sleep.interruptions': 'INTERRUPCIONES',
        'sleep.latency': 'LATENCIA',
        'sleep.normalRange': 'Rango Normal',
        'sleep.timesWokenUp': 'Veces que despertó',
        'sleep.timeToFallAsleep': 'Tiempo para dormir',
        'sleep.stagesDistribution': 'Distribución de etapas',
        'sleep.totalTimeInBed': 'Tiempo total en cama',
        'sleep.overallSleepScore': 'Puntuación de Sueño',
        'sleep.excellent': 'Excelente',
        'sleep.fair': 'Regular',
        'sleep.poor': 'Pobre',
        'sleep.avgComparedToUsers': 'Comparación con el promedio de su edad.',
        'sleep.hypnogram': 'Hipnograma de Sueño',
        'sleep.timeInfo': 'Info de Horarios',
        'sleep.bedIn': 'A la cama',
        'sleep.sleep': 'Dormido',
        'sleep.wakeUp': 'Despierto',
        'sleep.bedOut': 'Levantado',
        'sleep.trend': 'Tendencia de Sueño',
        'sleep.day': 'Diario',
        'sleep.weekly': 'Semanal',
        'sleep.monthly': 'Mensual',
        'sleep.vitalsCorrelation': 'Correlación de Vitales',
        'sleep.avgHr': 'FC Promedio',
        'sleep.avgResp': 'FR Promedio',
        'sleep.avgSpO2': 'SpO2 Promedio',
        'settings.title': 'Configuración',
        'settings.subtitle': 'Preferencias del Sistema',
        'settings.language': 'Idioma',
        'settings.selectLanguage': 'Seleccionar idioma',
        'settings.description': 'Configurar preferencias del entorno.',
        'settings.dataManagement': 'Gestión de Datos',
        'settings.dataRetention': 'Retención de Datos (Días)',
        'settings.autoBackup': 'Copia de Seguridad Automática',
        'settings.langUpdateNote': 'Cambiar el idioma actualizará toda la interfaz de la aplicación al idioma seleccionado.',
        'common.save': 'Guardar',
        'common.cancel': 'Cancelar',
        'common.bpm': 'BPM',
        'common.rpm': 'RPM',
        'error.loadingData': 'Error al cargar los datos.',
        'error.patientNotFound': 'Paciente no encontrado.',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('ko');

    const t = (key: string) => {
        return (translations[language] as any)[key] || (translations['en'] as any)[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
