import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ko' | 'en' | 'ja' | 'ch' | 'es';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    /**
     * Get localized text from an API data object with multiple language versions.
     * Example: getLocalizedText({ ko: "한국어", en: "English" }) returns "English" if language is 'en'
     */
    getLocalizedText: (data: Record<string, string> | string | undefined | null, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    ko: {
        'dashboard.totalPatients': '전체 환자 수',
        'dashboard.activeAlerts': '현재 알람',
        'dashboard.criticalPatients': '위급 환자',
        'dashboard.devicesConnected': '연결된 장비',
        'dashboard.heartRateTitle': '심박수',
        'dashboard.breathingRateTitle': '호흡수',
        'dashboard.sortedByUrgency': '긴급도 순 정렬',
        'dashboard.heartEmergency': '심박 위급',
        'dashboard.breathingEmergency': '호흡 위급',
        'dashboard.fallDetected': '낙상 감지',
        'dashboard.headerTitle': '의료 모니터링 대시보드',
        'dashboard.headerSubtitle': '환자 모니터링 시스템',
        'sidebar.dashboard': '통합 대시보드',
        'sidebar.patientList': '환자 목록',
        'sidebar.alertHistory': '알림 기록',
        'sidebar.sleepManagement': '수면 관리',
        'sidebar.registration': '환자 등록',
        'sidebar.militaryGps': 'GPS 위치 추적',
        'sidebar.settings': '설정',
        'sidebar.userName': '김민준 박사',
        'sidebar.role': '시스템 관리자',
        'sidebar.brandTitle': '레이더 모니터',
        'sidebar.brandSubtitle': '60GHz 시스템',
        'header.systemOnline': '온라인',
        'header.systemOffline': '오프라인',
        'header.exportReport': '보고서 내보내기',
        'header.liveMonitor': '라이브 모니터',
        'alerts.title': '긴급 알림',
        'alerts.description': '과거 발생한 알림 내역을 확인하는 페이지입니다.',
        'alerts.patient': '환자',
        'alerts.value': '수치',
        'alerts.acknowledge': '확인',
        'alerts.resolve': '해결',
        'alerts.currentValue': '현재',
        'alerts.threshold': '임계값',
        'alerts.viewAll': '전체 보기',
        'table.patientId': '환자 ID',
        'table.heartRate': '심박수',
        'table.breathingRate': '호흡수',
        'table.sleepState': '수면 상태',
        'table.alertStatus': '알림 상태',
        'table.deviceStatus': '장비 상태',
        'table.lastUpdated': '최근 업데이트',
        'table.actions': '작업',
        'table.viewDetails': '상세 보기',
        'table.searchPlaceholder': 'ID 또는 이름으로 검색...',
        'table.showing': '표시 중',
        'table.to': '내용',
        'table.of': '건 중',
        'table.patients': '명의 환자',
        'table.filteredFrom': '필터링됨 (전체',
        'table.total': '총',
        'table.previous': '이전',
        'table.next': '다음',
        'table.page': '페이지',
        'table.registrationDate': '등록일',
        'table.overview': '환자 개요',
        'table.realTime': '모든 환자의 실시간 모니터링',
        'table.bloodType': '혈액형',
        'status.critical': '위급',
        'status.warning': '경고',
        'status.caution': '주의',
        'status.normal': '정상',
        'status.medium': '주의',
        'status.stable': '안정',
        'status.online': '온라인',
        'status.offline': '오프라인',
        'status.error': '오류',
        'status.maintenance': '점검 중',
        'status.connected': '연결됨',
        'status.disconnected': '연결 끊김',
        'status.labelPrefix': '상태: ',
        'time.justNow': '방금 전',
        'time.secondsAgo': '초 전',
        'time.minutesAgo': '분 전',
        'time.hour': '시간',
        'time.minute': '분',
        'detail.back': '이전으로',
        'detail.patientInfo': '환자 정보',
        'detail.gender': '성별',
        'detail.age': '연령',
        'detail.room': '병실',
        'detail.admissionDate': '입원일',
        'detail.admissionStatus': '입원 일차',
        'detail.diagnosis': '진단명',
        'detail.doctor': '주치의',
        'detail.hr': '심박수',
        'detail.stress': '스트레스',
        'detail.rr': '호흡수',
        'detail.sleepEfficiency': '수면 효율',
        'detail.connection': '연결 상태',
        'detail.optimized': '최적화',
        'detail.sleepAnalysis': '수면 상세 분석',
        'detail.hrMonitoring': '심박수 모니터링',
        'detail.rrMonitoring': '호흡수 모니터링',
        'detail.detailedRecord': '환자 상세 기록',
        'detail.address': '주소',
        'detail.emergencyContact': '비상 연락처',
        'detail.allergies': '알레르기',
        'detail.clinicalFindings': '임상 소견',
        'detail.underlyingDisease': '기저 질환',
        'detail.medications': '복용 약물',
        'detail.diet': '식단',
        'detail.memo': '메모',
        'detail.alerts': '위험 알림',
        'detail.deepSleep': '깊은 수면',
        'detail.lightSleep': '얕은 수면',
        'detail.remSleep': 'REM 수면',
        'detail.awake': '깨어남',
        'detail.days': '일',
        'detail.yearsOld': '세',
        'detail.roomNumber': '호',
        'detail.observe': '관찰 필요',
        'detail.none': '없음',
        'detail.checkMedication': '처방 내역 확인 필요',
        'detail.generalDiet': '일반식 (병원식)',
        'detail.noSpecialMemo': '특이사항 없음',
        'detail.nurse': '담당 간호사',
        'detail.guardian': '보호자',
        'gender.male': '남',
        'gender.female': '여',
        'gps.title': 'GPS 위치 추적',
        'gps.description': '연결된 60GHz 장비의 실시간 위치를 확인합니다.',
        'registration.title': '환자 정보 등록',
        'registration.description': '새로운 환자 또는 장비 정보를 등록하는 페이지입니다.',
        'registration.basicInfo': '기본 정보',
        'registration.patientName': '환자명',
        'registration.dob': '생년월일',
        'registration.gender': '성별',
        'registration.select': '선택하세요',
        'registration.male': '남성',
        'registration.female': '여성',
        'registration.contact': '환자 연락처',
        'registration.patientNameEn': '성함 (영어)',
        'registration.patientCode': '환자 코드',
        'registration.emergencyPhone': '비상 연락처',
        'registration.wardId': '병동 ID',
        'registration.roomNumber': '병실 호수',
        'registration.bedNumber': '병상 번호',
        'registration.admissionDate': '입원일',
        'registration.status': '상태',
        'registration.roomWard': '객실',
        'registration.deviceInfo': '장치 정보',
        'registration.deviceId': '장치 ID',
        'registration.sensorType': '센서 유형',
        'registration.radar60ghz': '60GHz 레이더',
        'registration.careFacility': '관리 시설',
        'registration.facilityName': '시설명',
        'registration.registrationDate': '등록일',
        'registration.reset': '초기화',
        'registration.submit': '등록하기',
        'registration.success': '환자 정보가 등록되었습니다.',
        'sleep.title': '수면 관리',
        'sleep.description': '환자별 수면 패턴 및 품질 분석 페이지입니다.',
        'sleep.sessionSummary': '수면 요약',
        'sleep.lastNight': '지난 밤',
        'sleep.totalSleep': '총 수면 시간',
        'sleep.goal': '목표',
        'sleep.efficiency': '수면 효율',
        'sleep.interruptions': '깨어남 횟수',
        'sleep.latency': '입면 시간',
        'sleep.normalRange': '정상 범위',
        'sleep.timesWokenUp': '깨어난 횟수',
        'sleep.timeToFallAsleep': '잠들 때까지 걸린 시간',
        'sleep.stagesDistribution': '수면 단계 구성',
        'sleep.totalTimeInBed': '총 침대 체류 시간',
        'sleep.overallSleepScore': '종합 수면 점수',
        'sleep.excellent': '우수',
        'sleep.fair': '보통',
        'sleep.poor': '저조',
        'sleep.avgComparedToUsers': '동일 연령대 평균 대비 수치입니다.',
        'sleep.hypnogram': '수면 단계 그래프',
        'sleep.timeInfo': '수면 시간 정보',
        'sleep.bedIn': '취침 준비',
        'sleep.sleep': '수면 시작',
        'sleep.wakeUp': '기상 시간',
        'sleep.bedOut': '침대 이탈',
        'sleep.trend': '수면 트렌드',
        'sleep.day': '일별',
        'sleep.weekly': '주간',
        'sleep.monthly': '월간',
        'sleep.vitalsCorrelation': '활력 징후 상관관계',
        'sleep.avgHr': '평균 심박수',
        'sleep.avgResp': '평균 호흡수',
        'sleep.avgSpO2': '평균 산소포화도',
        'settings.title': '설정',
        'settings.subtitle': '시스템 환경 설정',
        'settings.language': '언어 설정',
        'settings.selectLanguage': '언어 선택',
        'settings.description': '시스템 환경 설정을 변경하는 페이지입니다.',
        'settings.langUpdateNote': '언어를 변경하면 전체 앱의 인터페이스가 선택한 언어로 변경됩니다.',
        'common.save': '저장',
        'common.cancel': '취소',
        'common.today': '오늘',
        'common.reset': '초기화',
        'common.collapse': '접기',
        'common.bpm': 'BPM',
        'common.rpm': 'RPM',
        'error.loadingData': '데이터를 불러오는 중 오류가 발생했습니다.',
        'error.patientNotFound': '환자 정보를 찾을 수 없습니다.',
        'notifications.table.date': '날짜',
        'notifications.table.system': '시스템',
        'notifications.table.patientId': '환자 ID',
        'notifications.table.category': '분류',
        'notifications.table.type': '유형',
        'notifications.table.status': '상태',
        'notifications.table.details': '상세 내용',
        'notifications.table.noLogs': '표시할 로그가 없습니다.',
        'notifications.table.success': '성공',
        'notifications.table.fail': '실패',
        'notifications.history': '알림 기록',
        'notifications.logs': '로그',
        'filter.allStatus': '전체 상태',
        'filter.active': '활성',
        'filter.active.mobile': '활성',
        'filter.discharged': '퇴원',
        'filter.discharged.mobile': '퇴원',
        'filter.transferred': '전원',
        'filter.transferred.mobile': '전원',
        'filter.searchPlaceholder': '이름 또는 ID로 검색',
        'filter.statusActive': 'ACTIVE',
        'filter.statusDischarged': 'DISCHARGED',
        'filter.statusTransferred': 'TRANSFERRED',
        'table.sleep': '수면',
        'table.openSleepPage': '수면 페이지 열기',
        'table.viewPatientDetails': '환자 상세 보기',
        'patientStatus.label': '환자 상태',
        'patientStatus.active': '입원중',
        'patientStatus.discharged': '퇴원',
        'patientStatus.transferred': '전원',
        'patientStatus.updateSuccess': '상태가 업데이트되었습니다',
        'notifications.system.radar': '레이더 모니터링 시스템',
        'notifications.system.status': '시스템 상태 점검',
        'notifications.system.backup': '데이터 백업 서비스',
        'notifications.category.hr': '심박수 모니터링',
        'notifications.category.rr': '호흡 모니터링',
        'notifications.category.fall': '낙상 감지',
        'notifications.category.sysStatus': '시스템 관리/상태 확인',
        'notifications.category.sysBackup': '시스템 관리/백업',
        'notifications.category.monitoring': '모니터링',
        'notifications.category.registration': '환자 등록/정보 생성',
        'notifications.category.emergency': '긴급 알림',
        'notifications.category.warning': '경고',
        'notifications.type.hrCritical': '위급_심박수',
        'notifications.type.hrWarning': '경고_심박수',
        'notifications.type.hrCaution': '주의_심박수',
        'notifications.type.rrCritical': '위급_호흡수',
        'notifications.type.rrWarning': '경고_호흡수',
        'notifications.type.rrCaution': '주의_호흡수',
        'notifications.type.fallDetected': '낙상_감지',
        'notifications.type.event': '알림_이벤트',
        'notifications.type.sysCheck': '시스템_상태_점검',
        'notifications.type.backup': '데이터_백업',
        'notifications.type.patientReg': '환자_등록',
        'notifications.details.hrHigh': '심박수가 위험 기준치를 초과했습니다',
        'notifications.details.rrLow': '호흡수가 안전 기준치 이하입니다',
        'notifications.details.fallEmergency': '낙상 감지됨, 응급 프로토콜 시작',
        'notifications.details.ack': '알림 확인됨',
        'notifications.details.resolved': '알림 해결됨',
        'notifications.details.sysNormal': '모든 시스템 정상 작동 중',
        'notifications.details.backupFail': '백업 실패 - 연결 시간 초과',
        'notifications.details.regSuccess': '새 환자가 성공적으로 등록되었습니다',
        'monitoring.range.5m': '5분',
        'monitoring.range.15m': '15분',
        'monitoring.range.30m': '30분',
        'monitoring.range.1h': '1시간',
        'monitoring.range.6h': '6시간',
        'monitoring.range.24h': '24시간',
        'gps.searchPlaceholder': '환자명 / 환자ID / 장비ID 검색...',
        'gps.noResults': '검색 결과가 없습니다',
        'gps.autoTracking': '자동 추적',
        'gps.autoTracking.mobile': '자동 추적',
        'gps.myLocation': '내 위치 표시',
        'gps.myLocation.mobile': '내 위치',
        'gps.errorSupport': '브라우저가 위치 정보를 지원하지 않습니다.',
        'gps.errorFetch': '위치 정보를 가져올 수 없습니다.',
        'gps.errorPermission': '위치 정보 접근 권한이 거부되었습니다. 브라우저 설정에서 허용해주세요.',
        'gps.errorUnavailable': '위치 정보를 사용할 수 없습니다.',
        'gps.errorTimeout': '위치 정보 요청 시간이 초과되었습니다.',
        'gps.errorTracking': '실시간 추적 중 오류가 발생했습니다.',
        'gps.userLocation': '내 위치',
        'gps.fixLocation': '이 위치 고정',
        'gps.assignedPatient': '담당 환자',
        'gps.signalStatus': '신호 상태',
        'gps.accuracy': '정확도',
        'gps.activeDevices': '활성 장치',
        'gps.uptime': '가동 시간',
        'gps.horizontalPrecision': '수평 정밀도',
        'gps.monitoring247': '24/7 모니터링',
        'common.relationship.spouse': '배우자',
        'common.relationship.child': '자녀',
        'common.relationship.parent': '부모',
        'common.relationship.guardian': '보호자',
        'common.hospital': '국민간호병원',
        'common.warning': '경고',
        'common.noResults': '검색 결과가 없습니다',
        'common.unknown': '알 수 없음',
        'status.abnormal': '비정상',
        'dashboard.lastUpdated': '마지막 업데이트',
        'dashboard.usingCachedData': '캐시된 데이터 사용 중',
        'alerts.msg.hrExceeded': '심박수가 임계치를 초과했습니다',
        'alerts.msg.rrOutOfRange': '호흡수가 정상 범위를 벗어났습니다',
        'alerts.msg.fallDetected': '낙상이 감지되었습니다',
        'alerts.msg.hrLow': '심박수가 위험 기준치 이하입니다',
        'alerts.msg.rrHigh': '호흡수가 위험 기준치를 초과했습니다',
    },
    en: {
        'dashboard.totalPatients': 'Total Patients',
        'dashboard.activeAlerts': 'Active Alerts',
        'dashboard.criticalPatients': 'Critical Patients',
        'dashboard.devicesConnected': 'Devices Connected',
        'dashboard.heartRateTitle': 'Heart Rate',
        'dashboard.breathingRateTitle': 'Breathing Rate',
        'dashboard.sortedByUrgency': 'Sorted by Urgency',
        'dashboard.heartEmergency': 'Heart Emergency',
        'dashboard.breathingEmergency': 'Breathing Emergency',
        'dashboard.fallDetected': 'Fall Detected',
        'dashboard.headerTitle': 'Medical Monitoring Dashboard',
        'dashboard.headerSubtitle': 'Patient Monitoring System',
        'sidebar.dashboard': 'Dashboard',
        'sidebar.patientList': 'Patient List',
        'sidebar.alertHistory': 'Alert History',
        'sidebar.sleepManagement': 'Sleep Management',
        'sidebar.registration': 'Patient Registration',
        'sidebar.militaryGps': 'GPS Tracking',
        'sidebar.settings': 'Settings',
        'sidebar.userName': 'Dr. Kim Min-jun',
        'sidebar.role': 'System Administrator',
        'sidebar.brandTitle': 'RADAR MONITOR',
        'sidebar.brandSubtitle': '60GHz SYSTEM',
        'header.systemOnline': 'Online',
        'header.systemOffline': 'Offline',
        'header.exportReport': 'Export Report',
        'header.liveMonitor': 'Live Monitor',
        'alerts.title': 'Emergency Alerts',
        'alerts.description': 'View history of past alerts and notifications.',
        'alerts.patient': 'Patient',
        'alerts.value': 'Value',
        'alerts.acknowledge': 'Acknowledge',
        'alerts.resolve': 'Resolve',
        'alerts.currentValue': 'Current',
        'alerts.threshold': 'Threshold',
        'alerts.viewAll': 'View All',
        'table.patientId': 'Patient ID',
        'table.heartRate': 'Heart Rate',
        'table.breathingRate': 'Breathing Rate',
        'table.sleepState': 'Sleep State',
        'table.alertStatus': 'Alert Status',
        'table.deviceStatus': 'Device Status',
        'table.lastUpdated': 'Last Updated',
        'table.actions': 'Actions',
        'table.viewDetails': 'View Details',
        'table.searchPlaceholder': 'Search by ID or Name...',
        'table.showing': 'Showing',
        'table.to': 'to',
        'table.of': 'of',
        'table.patients': 'patients',
        'table.filteredFrom': 'filtered from',
        'table.total': 'total',
        'table.previous': 'Previous',
        'table.next': 'Next',
        'table.page': 'Page',
        'table.registrationDate': 'Registration Date',
        'table.overview': 'Patient Overview',
        'table.realTime': 'Real-time monitoring of all patients',
        'table.bloodType': 'Blood Type',
        'status.critical': 'Critical',
        'status.warning': 'Warning',
        'status.caution': 'Caution',
        'status.normal': 'Normal',
        'status.medium': 'Medium',
        'status.stable': 'Stable',
        'status.online': 'Online',
        'status.offline': 'Offline',
        'status.error': 'Error',
        'status.maintenance': 'Maintenance',
        'status.connected': 'Connected',
        'status.disconnected': 'Disconnected',
        'status.labelPrefix': 'Status: ',
        'time.justNow': 'Just now',
        'time.secondsAgo': 's ago',
        'time.minutesAgo': 'm ago',
        'time.hour': 'h',
        'time.minute': 'm',
        'detail.back': 'Back',
        'detail.patientInfo': 'Patient Info',
        'detail.gender': 'Gender',
        'detail.age': 'Age',
        'detail.room': 'Room',
        'detail.admissionDate': 'Admission Date',
        'detail.admissionStatus': 'Admission Day',
        'detail.diagnosis': 'Diagnosis',
        'detail.doctor': 'Doctor',
        'detail.hr': 'Heart Rate',
        'detail.stress': 'Stress Index',
        'detail.rr': 'Breathing Rate',
        'detail.sleepEfficiency': 'Sleep Efficiency',
        'detail.connection': 'Connection Status',
        'detail.optimized': 'Optimized',
        'detail.sleepAnalysis': 'Sleep Record Analysis',
        'detail.hrMonitoring': 'Heart Rate Monitoring',
        'detail.rrMonitoring': 'Breathing Rate Monitoring',
        'detail.detailedRecord': 'Detailed Record',
        'detail.address': 'Address',
        'detail.emergencyContact': 'Emergency Contact',
        'detail.allergies': 'Allergies',
        'detail.clinicalFindings': 'Clinical Findings',
        'detail.underlyingDisease': 'Underlying Disease',
        'detail.medications': 'Medications',
        'detail.diet': 'Diet',
        'detail.memo': 'Memo',
        'detail.alerts': 'Emergency Alerts',
        'detail.deepSleep': 'Deep Sleep',
        'detail.lightSleep': 'Light Sleep',
        'detail.remSleep': 'REM Sleep',
        'detail.awake': 'Awake',
        'detail.days': 'days',
        'detail.yearsOld': 'yo',
        'detail.roomNumber': '',
        'detail.observe': 'Needs Observation',
        'detail.none': 'None',
        'detail.checkMedication': 'Contact Pharmacy',
        'detail.generalDiet': 'General Diet',
        'detail.noSpecialMemo': 'No special notes',
        'detail.nurse': 'Nurse',
        'detail.guardian': 'Guardian',
        'gender.male': 'Male',
        'gender.female': 'Female',
        'gps.title': 'GPS Tracking',
        'gps.description': 'Real-time location monitoring of connected 60GHz devices.',
        'registration.title': 'Patient Registration',
        'registration.description': 'Register new patient or equipment information.',
        'registration.basicInfo': 'Basic Information',
        'registration.patientName': 'Patient Name',
        'registration.dob': 'Date of Birth',
        'registration.gender': 'Gender',
        'registration.select': 'Select...',
        'registration.male': 'Male',
        'registration.female': 'Female',
        'registration.contact': 'Patient Contact',
        'registration.patientNameEn': 'Patient Name (EN)',
        'registration.patientCode': 'Patient Code',
        'registration.emergencyPhone': 'Emergency Contact',
        'registration.wardId': 'Ward ID',
        'registration.roomNumber': 'Room Number',
        'registration.bedNumber': 'Bed Number',
        'registration.admissionDate': 'Admission Date',
        'registration.status': 'Status',
        'registration.roomWard': 'Room/Ward',
        'registration.deviceInfo': 'Device Information',
        'registration.deviceId': 'Device ID',
        'registration.sensorType': 'Sensor Type',
        'registration.radar60ghz': '60GHz Radar',
        'registration.careFacility': 'Care Facility',
        'registration.facilityName': 'Facility Name',
        'registration.registrationDate': 'Registration Date',
        'registration.reset': 'Reset',
        'registration.submit': 'Register Patient',
        'registration.success': 'Patient info registered.',
        'sleep.title': 'Sleep Management',
        'sleep.description': 'Analyze sleep patterns and quality per patient.',
        'sleep.sessionSummary': 'Sleep Session Summary',
        'sleep.lastNight': 'Last Night',
        'sleep.totalSleep': 'TOTAL SLEEP',
        'sleep.goal': 'Goal',
        'sleep.efficiency': 'EFFICIENCY',
        'sleep.interruptions': 'INTERRUPTIONS',
        'sleep.latency': 'LATENCY',
        'sleep.normalRange': 'Normal Range',
        'sleep.timesWokenUp': 'Times woken up',
        'sleep.timeToFallAsleep': 'Time to fall asleep',
        'sleep.stagesDistribution': 'Sleep Stages Distribution',
        'sleep.totalTimeInBed': 'Total time in bed',
        'sleep.overallSleepScore': 'Overall Sleep Score',
        'sleep.excellent': 'Excellent',
        'sleep.fair': 'Fair',
        'sleep.poor': 'Poor',
        'sleep.avgComparedToUsers': 'Average compared to users in this age group.',
        'sleep.hypnogram': 'Sleep Hypnogram',
        'sleep.timeInfo': 'Sleep Time Info',
        'sleep.bedIn': 'Bed in',
        'sleep.sleep': 'Sleep',
        'sleep.wakeUp': 'Wake up',
        'sleep.bedOut': 'Bed out',
        'sleep.trend': 'Sleep Trend',
        'sleep.day': 'Day',
        'sleep.weekly': 'Weekly',
        'sleep.monthly': 'Monthly',
        'sleep.vitalsCorrelation': 'Vitals Correlation',
        'sleep.avgHr': 'Avg HR',
        'sleep.avgResp': 'Avg Resp',
        'sleep.avgSpO2': 'Avg SpO2',
        'settings.title': 'Settings',
        'settings.subtitle': 'System Preferences',
        'settings.language': 'Language',
        'settings.selectLanguage': 'Select language',
        'settings.description': 'Configure system environment settings.',
        'settings.langUpdateNote': 'Changing the language will update the entire app interface to the selected language.',
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.today': 'Today',
        'common.reset': 'Reset',
        'common.bpm': 'BPM',
        'common.rpm': 'RPM',
        'error.loadingData': 'An error occurred while loading data.',
        'error.patientNotFound': 'Patient information not found.',
        'notifications.table.date': 'Date',
        'notifications.table.system': 'System',
        'notifications.table.patientId': 'Patient ID',
        'notifications.table.category': 'Category',
        'notifications.table.type': 'Type',
        'notifications.table.status': 'Status',
        'notifications.table.details': 'Details',
        'notifications.table.noLogs': 'No logs to display.',
        'notifications.table.success': 'Success',
        'notifications.table.fail': 'Fail',
        'notifications.history': 'Notification History',
        'notifications.logs': 'Notification Logs',
        'filter.allStatus': 'All Status',
        'filter.active': 'Active',
        'filter.active.mobile': 'Active',
        'filter.discharged': 'Discharged',
        'filter.discharged.mobile': 'Disc.',
        'filter.transferred': 'Transferred',
        'filter.transferred.mobile': 'Trans.',
        'filter.searchPlaceholder': 'Search by name or ID',
        'filter.statusActive': 'ACTIVE',
        'filter.statusDischarged': 'DISCHARGED',
        'filter.statusTransferred': 'TRANSFERRED',
        'table.sleep': 'Sleep',
        'table.openSleepPage': 'Open Sleep Page',
        'table.viewPatientDetails': 'View Patient Details',
        'patientStatus.label': 'Patient Status',
        'patientStatus.active': 'Admitted',
        'patientStatus.discharged': 'Discharged',
        'patientStatus.transferred': 'Transferred',
        'patientStatus.updateSuccess': 'Status updated successfully',
        'notifications.system.radar': 'Radar Monitoring System',
        'notifications.system.status': 'System Status Check',
        'notifications.system.backup': 'Data Backup Service',
        'notifications.category.hr': 'Heart Rate Monitoring',
        'notifications.category.rr': 'Breathing Monitoring',
        'notifications.category.fall': 'Fall Detection',
        'notifications.category.sysStatus': 'System Mgmt/Status',
        'notifications.category.sysBackup': 'System Mgmt/Backup',
        'notifications.category.monitoring': 'Monitoring',
        'notifications.category.registration': 'Patient Reg/Info',
        'notifications.category.emergency': 'Emergency Alert',
        'notifications.category.warning': 'Warning',
        'notifications.type.hrCritical': 'HR_CRITICAL',
        'notifications.type.hrWarning': 'HR_WARNING',
        'notifications.type.hrCaution': 'HR_CAUTION',
        'notifications.type.rrCritical': 'RR_CRITICAL',
        'notifications.type.rrWarning': 'RR_WARNING',
        'notifications.type.rrCaution': 'RR_CAUTION',
        'notifications.type.fallDetected': 'FALL_DETECTED',
        'notifications.type.event': 'ALERT_EVENT',
        'notifications.type.sysCheck': 'SYSTEM_CHECK',
        'notifications.type.backup': 'DATA_BACKUP',
        'notifications.type.patientReg': 'PATIENT_REG',
        'notifications.details.hrHigh': 'Heart rate exceeded danger threshold',
        'notifications.details.rrLow': 'Breathing rate below safety threshold',
        'notifications.details.fallEmergency': 'Fall detected, starting emergency protocol',
        'notifications.details.ack': 'Alert acknowledged',
        'notifications.details.resolved': 'Alert resolved',
        'notifications.details.sysNormal': 'All systems operating normally',
        'notifications.details.backupFail': 'Backup failed - Connection timeout',
        'notifications.details.regSuccess': 'New patient registered successfully',
        'monitoring.range.5m': '5m',
        'monitoring.range.15m': '15m',
        'monitoring.range.30m': '30m',
        'monitoring.range.1h': '1h',
        'monitoring.range.6h': '6h',
        'monitoring.range.24h': '24h',
        'gps.searchPlaceholder': 'Search patient / ID / Device...',
        'gps.noResults': 'No results found',
        'gps.autoTracking': 'Auto Tracking',
        'gps.autoTracking.mobile': 'Auto Track',
        'gps.myLocation': 'Show My Location',
        'gps.myLocation.mobile': 'Location',
        'gps.errorSupport': 'Browser does not support geolocation.',
        'gps.errorFetch': 'Unable to fetch location.',
        'gps.errorPermission': 'Location permission denied. Please allow in settings.',
        'gps.errorUnavailable': 'Location information is unavailable.',
        'gps.errorTimeout': 'Location request timed out.',
        'gps.errorTracking': 'Error occurred during real-time tracking.',
        'gps.userLocation': 'My Location',
        'gps.fixLocation': 'Fix this location',
        'gps.assignedPatient': 'Assigned Patient',
        'gps.signalStatus': 'Signal Status',
        'gps.accuracy': 'Accuracy',
        'gps.activeDevices': 'Active Devices',
        'gps.uptime': 'System Uptime',
        'gps.horizontalPrecision': 'Horizontal precision',
        'gps.monitoring247': '24/7 Monitoring',
        'common.relationship.spouse': 'Spouse',
        'common.relationship.child': 'Child',
        'common.relationship.parent': 'Parent',
        'common.relationship.guardian': 'Guardian',
        'common.hospital': 'National Nursing Hospital',
        'common.warning': 'Warning',
        'common.noResults': 'No results found',
        'common.collapse': 'Collapse',
        'common.unknown': 'Unknown',
        'status.abnormal': 'Abnormal',
        'dashboard.lastUpdated': 'Last updated',
        'dashboard.usingCachedData': 'Using cached data',
        'alerts.msg.hrExceeded': 'Heart rate exceeded threshold',
        'alerts.msg.rrOutOfRange': 'Respiratory rate out of normal range',
        'alerts.msg.fallDetected': 'Fall detected',
        'alerts.msg.hrLow': 'Heart rate below danger threshold',
        'alerts.msg.rrHigh': 'Respiratory rate exceeded danger threshold',
    },
    ja: {
        'dashboard.totalPatients': '全患者数',
        'dashboard.activeAlerts': '現在のアラート',
        'dashboard.criticalPatients': '危篤患者',
        'dashboard.devicesConnected': '接続デバイス',
        'dashboard.heartRateTitle': '心拍数',
        'dashboard.breathingRateTitle': '呼吸数',
        'dashboard.sortedByUrgency': '緊急度順',
        'dashboard.heartEmergency': '心拍緊急',
        'dashboard.breathingEmergency': '呼吸緊急',
        'dashboard.fallDetected': '転倒検知',
        'dashboard.headerTitle': '医療モニタリングダッシュボード',
        'dashboard.headerSubtitle': '患者監視システム',
        'sidebar.dashboard': '統合ダッシュボード',
        'sidebar.patientList': '患者リスト',
        'sidebar.alertHistory': '通知履歴',
        'sidebar.sleepManagement': '睡眠管理',
        'sidebar.registration': '患者登録',
        'sidebar.militaryGps': 'GPS位置追跡',
        'sidebar.settings': '設定',
        'sidebar.userName': '金民俊 博士',
        'sidebar.role': 'システム管理者',
        'sidebar.brandTitle': 'レーダーモニター',
        'sidebar.brandSubtitle': '60GHzシステム',
        'header.systemOnline': 'オンライン',
        'header.systemOffline': 'オフライン',
        'header.exportReport': 'レポート出力',
        'header.liveMonitor': 'ライブモニター',
        'alerts.title': '緊急通知',
        'alerts.description': '過去の通知履歴を確認するページです。',
        'alerts.patient': '患者',
        'alerts.value': '数値',
        'alerts.acknowledge': '確認',
        'alerts.resolve': '解決',
        'alerts.currentValue': '現在',
        'alerts.threshold': 'しきい値',
        'alerts.viewAll': 'すべて表示',
        'table.patientId': '患者ID',
        'table.heartRate': '心拍数',
        'table.breathingRate': '呼吸数',
        'table.sleepState': '睡眠状態',
        'table.alertStatus': '通知状態',
        'table.deviceStatus': 'デバイス状態',
        'table.lastUpdated': '最終更新',
        'table.actions': '操作',
        'table.viewDetails': '詳細表示',
        'table.searchPlaceholder': 'IDまたは名前で検索...',
        'table.showing': '表示中',
        'table.to': '〜',
        'table.of': '/',
        'table.patients': '人の患者',
        'table.filteredFrom': 'フィルタリング済み (全',
        'table.total': '人中)',
        'table.previous': '前へ',
        'table.next': '次へ',
        'table.page': 'ページ',
        'table.registrationDate': '登録日',
        'table.overview': '患者概要',
        'table.realTime': '全患者のリアルタイム監視',
        'table.bloodType': '血液型',
        'status.critical': '危篤',
        'status.warning': '警告',
        'status.caution': '注意',
        'status.normal': '正常',
        'status.medium': '注意',
        'status.stable': '安定',
        'status.online': 'オンライン',
        'status.offline': 'オフライン',
        'status.error': 'エラー',
        'status.maintenance': 'メンテナンス中',
        'status.connected': '接続済み',
        'status.disconnected': '切断',
        'status.labelPrefix': '状態: ',
        'time.justNow': '今',
        'time.secondsAgo': '秒前',
        'time.minutesAgo': '分前',
        'time.hour': '時間',
        'time.minute': '分',
        'detail.back': '戻る',
        'detail.patientInfo': '患者情報',
        'detail.gender': '性別',
        'detail.age': '年齢',
        'detail.room': '病室',
        'detail.admissionDate': '入院日',
        'detail.admissionStatus': '入院日数',
        'detail.diagnosis': '診断名',
        'detail.doctor': '主治医',
        'detail.hr': '心拍数',
        'detail.stress': 'ストレス',
        'detail.rr': '呼吸数',
        'detail.sleepEfficiency': '睡眠効率',
        'detail.connection': '接続状態',
        'detail.optimized': '最適化',
        'detail.sleepAnalysis': '睡眠詳細分析',
        'detail.hrMonitoring': '心拍数モニタリング',
        'detail.rrMonitoring': '呼吸数モニタリング',
        'detail.detailedRecord': '患者詳細記録',
        'detail.address': '住所',
        'detail.emergencyContact': '緊急連絡先',
        'detail.allergies': 'アレルギー',
        'detail.clinicalFindings': '臨床所見',
        'detail.underlyingDisease': '基礎疾患',
        'detail.medications': '服用薬',
        'detail.diet': '食事',
        'detail.memo': 'メモ',
        'detail.alerts': '危険通知',
        'detail.deepSleep': '深い睡眠',
        'detail.lightSleep': '浅い睡眠',
        'detail.remSleep': 'レム睡眠',
        'detail.awake': '覚醒',
        'detail.days': '日',
        'detail.yearsOld': '歳',
        'detail.roomNumber': '号',
        'detail.observe': '観察必要',
        'detail.none': 'なし',
        'detail.checkMedication': '処方内容の確認が必要',
        'detail.generalDiet': '一般食',
        'detail.noSpecialMemo': '特記事項なし',
        'detail.nurse': '担当看護師',
        'detail.guardian': '保護者',
        'gender.male': '男',
        'gender.female': '女',
        'gps.title': 'GPS位置追跡',
        'gps.description': '接続された60GHzデバイスのリアルタイム位置を確認します。',
        'registration.title': '患者情報の登録',
        'registration.description': '新しい患者またはデバイス情報の登録ページです。',
        'registration.basicInfo': '基本情報',
        'registration.patientName': '患者名',
        'registration.dob': '生年月日',
        'registration.gender': '性別',
        'registration.select': '選択してください',
        'registration.male': '男性',
        'registration.female': '女性',
        'registration.contact': '患者連絡先',
        'registration.patientNameEn': '氏名 (英語)',
        'registration.patientCode': '患者コード',
        'registration.emergencyPhone': '緊急連絡先',
        'registration.wardId': '病棟ID',
        'registration.roomNumber': '病室番号',
        'registration.bedNumber': 'ベッド番号',
        'registration.admissionDate': '入院日',
        'registration.status': '状態',
        'registration.roomWard': '客室',
        'registration.deviceInfo': 'デバイス情報',
        'registration.deviceId': 'デバイスID',
        'registration.sensorType': 'センサータイプ',
        'registration.radar60ghz': '60GHzレーダー',
        'registration.careFacility': '管理施設',
        'registration.facilityName': '施設名',
        'registration.registrationDate': '登録日',
        'registration.reset': '初期化',
        'registration.submit': '登録する',
        'registration.success': '患者情報が登録されました。',
        'sleep.title': '睡眠管理',
        'sleep.description': '患者別睡眠パターンおよび品質分析ページです。',
        'sleep.sessionSummary': '睡眠サマリー',
        'sleep.lastNight': '昨夜',
        'sleep.totalSleep': '総睡眠時間',
        'sleep.goal': '目標',
        'sleep.efficiency': '睡眠効率',
        'sleep.interruptions': '中途覚醒',
        'sleep.latency': '入眠潜時',
        'sleep.normalRange': '正常範囲',
        'sleep.timesWokenUp': '覚醒回数',
        'sleep.timeToFallAsleep': '入眠時間',
        'sleep.stagesDistribution': '睡眠段階構成',
        'sleep.totalTimeInBed': '総就床時間',
        'sleep.overallSleepScore': '総合睡眠スコア',
        'sleep.excellent': '非常に良い',
        'sleep.fair': '普通',
        'sleep.poor': '低い',
        'sleep.avgComparedToUsers': '同年齢層の平均との比較値です。',
        'sleep.hypnogram': '睡眠段階グラフ',
        'sleep.timeInfo': '睡眠時間情報',
        'sleep.bedIn': '就床',
        'sleep.sleep': '入眠',
        'sleep.wakeUp': '起床',
        'sleep.bedOut': '離床',
        'sleep.trend': '睡眠トレンド',
        'sleep.day': '日別',
        'sleep.weekly': '週間',
        'sleep.monthly': '月間',
        'sleep.vitalsCorrelation': 'バイタルサイン相関',
        'sleep.avgHr': '平均心拍数',
        'sleep.avgResp': '平均呼吸数',
        'sleep.avgSpO2': '平均SpO2',
        'settings.title': '設定',
        'settings.subtitle': 'システム設定',
        'settings.language': '言語設定',
        'settings.selectLanguage': '言語を選択',
        'settings.description': 'システム環境設定を変更するページです。',
        'settings.langUpdateNote': '言語を変更すると、アプリ全体のインターフェースが選択した言語に変更されます。',
        'common.save': '保存',
        'common.cancel': 'キャンセル',
        'common.today': '今日',
        'common.reset': 'リセット',
        'common.collapse': '折りたたむ',
        'common.bpm': 'BPM',
        'common.rpm': 'RPM',
        'error.loadingData': 'データの読み込み中にエラーが発生しました。',
        'error.patientNotFound': '患者情報が見つかりません。',
        'notifications.table.date': '日付',
        'notifications.table.system': 'システム',
        'notifications.table.patientId': '患者ID',
        'notifications.table.category': '分類',
        'notifications.table.type': 'タイプ',
        'notifications.table.status': '状態',
        'notifications.table.details': '詳細内容',
        'notifications.table.noLogs': '表示するログはありません。',
        'notifications.table.success': '成功',
        'notifications.table.fail': '失敗',
        'notifications.history': 'アラート履歴',
        'notifications.logs': 'ログ',
        'filter.allStatus': '全状態',
        'filter.active': '有効',
        'filter.active.mobile': '有効',
        'filter.discharged': '退院済み',
        'filter.discharged.mobile': '退院',
        'filter.transferred': '転員済み',
        'filter.transferred.mobile': '転員',
        'filter.searchPlaceholder': '名前またはIDで検索',
        'filter.statusActive': 'ACTIVE',
        'filter.statusDischarged': 'DISCHARGED',
        'filter.statusTransferred': 'TRANSFERRED',
        'table.sleep': '睡眠',
        'table.openSleepPage': '睡眠ページを開く',
        'table.viewPatientDetails': '患者詳細を表示',
        'patientStatus.label': '患者状態',
        'patientStatus.active': '入院中',
        'patientStatus.discharged': '退院',
        'patientStatus.transferred': '転員',
        'patientStatus.updateSuccess': '状態が更新されました',
        'notifications.system.radar': 'レーダー監視システム',
        'notifications.system.status': 'システム状態チェック',
        'notifications.system.backup': 'データバックアップサービス',
        'notifications.category.hr': '心拍数モニタリング',
        'notifications.category.rr': '呼吸数モニタリング',
        'notifications.category.fall': '転倒検知',
        'notifications.category.sysStatus': 'システム管理/状態確認',
        'notifications.category.sysBackup': 'システム管理/バックアップ',
        'notifications.category.monitoring': 'モニタリング',
        'notifications.category.registration': '患者登録/情報生成',
        'notifications.category.emergency': '緊急通知',
        'notifications.category.warning': '警告',
        'notifications.type.hrCritical': '緊急_心拍数',
        'notifications.type.hrWarning': '警告_心拍数',
        'notifications.type.hrCaution': '注意_心拍数',
        'notifications.type.rrCritical': '緊急_呼吸数',
        'notifications.type.rrWarning': '警告_呼吸数',
        'notifications.type.rrCaution': '注意_呼吸数',
        'notifications.type.fallDetected': '転倒_検知',
        'notifications.type.event': '通知_イベント',
        'notifications.type.sysCheck': 'システム_状態_チェック',
        'notifications.type.backup': 'データ_バックアップ',
        'notifications.type.patientReg': '患者_登録',
        'notifications.details.hrHigh': '心拍数が危険基準値を超えました',
        'notifications.details.rrLow': '呼吸数が安全基準値を下回っています',
        'notifications.details.fallEmergency': '転倒が検知されました。緊急プロトコルを開始します',
        'notifications.details.ack': '通知を確認しました',
        'notifications.details.resolved': '通知を解決しました',
        'notifications.details.sysNormal': 'すべてのシステムが正常に動作しています',
        'notifications.details.backupFail': 'バックアップ失敗 - 接続タイムアウト',
        'notifications.details.regSuccess': '新しい患者が正常に登録されました',
        'monitoring.range.5m': '5分',
        'monitoring.range.15m': '15分',
        'monitoring.range.30m': '30分',
        'monitoring.range.1h': '1時間',
        'monitoring.range.6h': '6時間',
        'monitoring.range.24h': '24時間',
        'gps.searchPlaceholder': '患者名 / 患者ID / デバイスIDを検索...',
        'gps.noResults': '検索結果がありません',
        'gps.autoTracking': '自動追跡',
        'gps.autoTracking.mobile': '自動追跡',
        'gps.myLocation': '現在地を表示',
        'gps.myLocation.mobile': '現在地',
        'gps.errorSupport': 'ブラウザが位置情報をサポートしていません。',
        'gps.errorFetch': '位置情報を取得できません。',
        'gps.errorPermission': '位置情報のアクセス権限が拒否されました。設定で許可してください。',
        'gps.errorUnavailable': '位置情報が利用できません。',
        'gps.errorTimeout': '位置情報の要求がタイムアウトしました。',
        'gps.errorTracking': 'リアルタイム追跡中にエラーが発生しました。',
        'gps.userLocation': '現在地',
        'gps.fixLocation': 'この位置を固定',
        'gps.assignedPatient': '担当患者',
        'gps.signalStatus': '信号状態',
        'gps.accuracy': '精度',
        'gps.activeDevices': 'アクティブデバイス',
        'gps.uptime': '稼働時間',
        'gps.horizontalPrecision': '水平精度',
        'gps.monitoring247': '24時間監視',
        'common.relationship.spouse': '配偶者',
        'common.relationship.child': '子供',
        'common.relationship.parent': '親',
        'common.relationship.guardian': '保護者',
        'common.hospital': '国民看護病院',
        'common.warning': '警告',
        'common.noResults': '検索結果がありません',
        'common.unknown': '不明',
        'status.abnormal': '異常',
        'dashboard.lastUpdated': '最終更新',
        'dashboard.usingCachedData': 'キャッシュデータを使用中',
        'alerts.msg.hrExceeded': '心拍数がしきい値を超えました',
        'alerts.msg.rrOutOfRange': '呼吸数が正常範囲を外れています',
        'alerts.msg.fallDetected': '転倒が検知されました',
        'alerts.msg.hrLow': '心拍数が危険基準値を下回っています',
        'alerts.msg.rrHigh': '呼吸数が危険基準値を超えました',
    },
    ch: {
        'dashboard.totalPatients': '患者总数',
        'dashboard.activeAlerts': '当前警报',
        'dashboard.criticalPatients': '危重患者',
        'dashboard.devicesConnected': '已连接设备',
        'dashboard.heartRateTitle': '心率',
        'dashboard.breathingRateTitle': '呼吸率',
        'dashboard.sortedByUrgency': '按紧急度排序',
        'dashboard.heartEmergency': '心率紧急',
        'dashboard.breathingEmergency': '呼吸紧急',
        'dashboard.fallDetected': '跌倒检测',
        'dashboard.headerTitle': '医疗监控仪表板',
        'dashboard.headerSubtitle': '患者监控系统',
        'sidebar.dashboard': '综合仪表板',
        'sidebar.patientList': '患者列表',
        'sidebar.alertHistory': '警报记录',
        'sidebar.sleepManagement': '睡眠管理',
        'sidebar.registration': '患者注册',
        'sidebar.militaryGps': 'GPS位置追踪',
        'sidebar.settings': '设置',
        'sidebar.userName': '金民俊 博士',
        'sidebar.role': '系统管理员',
        'sidebar.brandTitle': '雷达监控',
        'sidebar.brandSubtitle': '60GHz系统',
        'header.systemOnline': '在线',
        'header.systemOffline': '离线',
        'header.exportReport': '导出报告',
        'header.liveMonitor': '实时监控',
        'alerts.title': '紧急通知',
        'alerts.description': '查看过去警报记录的页面。',
        'alerts.patient': '患者',
        'alerts.value': '数值',
        'alerts.acknowledge': '确认',
        'alerts.resolve': '解决',
        'alerts.currentValue': '当前',
        'alerts.threshold': '临界值',
        'alerts.viewAll': '查看全部',
        'table.patientId': '患者ID',
        'table.heartRate': '心率',
        'table.breathingRate': '呼吸率',
        'table.sleepState': '睡眠状态',
        'table.alertStatus': '警报状态',
        'table.deviceStatus': '设备状态',
        'table.lastUpdated': '最后更新',
        'table.actions': '操作',
        'table.viewDetails': '查看详情',
        'table.searchPlaceholder': '通过ID或姓名搜索...',
        'table.showing': '显示',
        'table.to': '到',
        'table.of': '/',
        'table.patients': '名患者',
        'table.filteredFrom': '已过滤 (总共',
        'table.total': '名中的)',
        'table.previous': '上一页',
        'table.next': '下一页',
        'table.page': '页',
        'table.registrationDate': '注册日期',
        'table.overview': '患者概览',
        'table.realTime': '所有患者的实时监控',
        'table.bloodType': '血型',
        'status.critical': '危重',
        'status.warning': '警告',
        'status.caution': '注意',
        'status.normal': '正常',
        'status.medium': '注意',
        'status.stable': '稳定',
        'status.online': '在线',
        'status.offline': '离线',
        'status.error': '错误',
        'status.maintenance': '维护中',
        'status.connected': '已连接',
        'status.disconnected': '已断开',
        'status.labelPrefix': '状态: ',
        'time.justNow': '刚刚',
        'time.secondsAgo': '秒前',
        'time.minutesAgo': '分钟前',
        'time.hour': '小时',
        'time.minute': '分钟',
        'detail.back': '返回',
        'detail.patientInfo': '患者信息',
        'detail.gender': '性别',
        'detail.age': '年龄',
        'detail.room': '病房',
        'detail.admissionDate': '入院日期',
        'detail.admissionStatus': '入院天数',
        'detail.diagnosis': '诊断',
        'detail.doctor': '主治医生',
        'detail.hr': '心率',
        'detail.stress': '压力指数',
        'detail.rr': '呼吸率',
        'detail.sleepEfficiency': '睡眠效率',
        'detail.connection': '连接状态',
        'detail.optimized': '已优化',
        'detail.sleepAnalysis': '睡眠详细分析',
        'detail.hrMonitoring': '心率监控',
        'detail.rrMonitoring': '呼吸率监控',
        'detail.detailedRecord': '患者详细记录',
        'detail.address': '地址',
        'detail.emergencyContact': '紧急联系人',
        'detail.allergies': '过敏',
        'detail.clinicalFindings': '临床发现',
        'detail.underlyingDisease': '基础疾病',
        'detail.medications': '服用药物',
        'detail.diet': '饮食',
        'detail.memo': '备注',
        'detail.alerts': '危险通知',
        'detail.deepSleep': '深度睡眠',
        'detail.lightSleep': '浅度睡眠',
        'detail.remSleep': '快动眼睡眠',
        'detail.awake': '醒来',
        'detail.days': '天',
        'detail.yearsOld': '岁',
        'detail.roomNumber': '号',
        'detail.observe': '需要观察',
        'detail.none': '无',
        'detail.checkMedication': '需要确认处方',
        'detail.generalDiet': '普通饮食',
        'detail.noSpecialMemo': '无特殊备注',
        'detail.nurse': '护士',
        'detail.guardian': '监护人',
        'gender.male': '男',
        'gender.female': '女',
        'gps.title': 'GPS位置追踪',
        'gps.description': '实时监控已连接的60GHz设备位置。',
        'registration.title': '患者信息注册',
        'registration.description': '注册新患者或设备信息的页面।',
        'registration.basicInfo': '基本信息',
        'registration.patientName': '患者姓名',
        'registration.dob': '出生日期',
        'registration.gender': '性别',
        'registration.select': '请选择',
        'registration.male': '男性',
        'registration.female': '女性',
        'registration.contact': '患者联系方式',
        'registration.patientNameEn': '姓名 (英文)',
        'registration.patientCode': '患者代码',
        'registration.emergencyPhone': '紧急联系人',
        'registration.wardId': '病房 ID',
        'registration.roomNumber': '病房号',
        'registration.bedNumber': '床位号',
        'registration.admissionDate': '入院日期',
        'registration.status': '状态',
        'registration.roomWard': '客房',
        'registration.deviceInfo': '设备信息',
        'registration.deviceId': '设备ID',
        'registration.sensorType': '传感器类型',
        'registration.radar60ghz': '60GHz雷达',
        'registration.careFacility': '管理设施',
        'registration.facilityName': '设施名称',
        'registration.registrationDate': '注册日期',
        'registration.reset': '重置',
        'registration.submit': '注册',
        'registration.success': '患者信息已注册。',
        'sleep.title': '睡眠管理',
        'sleep.description': '按患者分析睡眠模式和质量的页面。',
        'sleep.sessionSummary': '睡眠摘要',
        'sleep.lastNight': '昨晚',
        'sleep.totalSleep': '总睡眠时间',
        'sleep.goal': '目标',
        'sleep.efficiency': '睡眠效率',
        'sleep.interruptions': '醒来次数',
        'sleep.latency': '入睡潜伏期',
        'sleep.normalRange': '正常范围',
        'sleep.timesWokenUp': '醒来次数',
        'sleep.timeToFallAsleep': '入睡所需时间',
        'sleep.stagesDistribution': '睡眠阶段分布',
        'sleep.totalTimeInBed': '总在床时间',
        'sleep.overallSleepScore': '综合睡眠评分',
        'sleep.excellent': '优秀',
        'sleep.fair': '一般',
        'sleep.poor': '较差',
        'sleep.avgComparedToUsers': '与同年龄段平均水平的对比值。',
        'sleep.hypnogram': '睡眠阶段图表',
        'sleep.timeInfo': '睡眠时间정보',
        'sleep.bedIn': '上床',
        'sleep.sleep': '入睡',
        'sleep.wakeUp': '醒来',
        'sleep.bedOut': '起床',
        'sleep.trend': '睡眠趋势',
        'sleep.day': '每日',
        'sleep.weekly': '每周',
        'sleep.monthly': '每月',
        'sleep.vitalsCorrelation': '生命体征相关性',
        'sleep.avgHr': '平均心率',
        'sleep.avgResp': '平均呼吸率',
        'sleep.avgSpO2': '平均血氧饱和度',
        'settings.title': '设置',
        'settings.subtitle': '系统偏好设置',
        'settings.language': '语言设置',
        'settings.selectLanguage': '选择语言',
        'settings.description': '配置系统环境设置的页面。',
        'settings.langUpdateNote': '更改语言将把整个应用程序界面更新为所选语言。',
        'common.save': '保存',
        'common.cancel': '取消',
        'common.today': '今天',
        'common.reset': '重置',
        'common.collapse': '折叠',
        'common.bpm': 'BPM',
        'common.rpm': 'RPM',
        'error.loadingData': '加载数据时出错。',
        'error.patientNotFound': '找不到患者信息。',
        'notifications.table.date': '日期',
        'notifications.table.system': '系统',
        'notifications.table.patientId': '患者ID',
        'notifications.table.category': '分类',
        'notifications.table.type': '类型',
        'notifications.table.status': '状态',
        'notifications.table.details': '详细内容',
        'notifications.table.noLogs': '没有可显示的日志。',
        'notifications.table.success': '成功',
        'notifications.table.fail': '失败',
        'notifications.history': '警报记录',
        'notifications.logs': '日志',
        'filter.allStatus': '全部状态',
        'filter.active': '活跃',
        'filter.active.mobile': '活跃',
        'filter.discharged': '出院',
        'filter.discharged.mobile': '出院',
        'filter.transferred': '转院',
        'filter.transferred.mobile': '转院',
        'filter.searchPlaceholder': '按姓名或ID搜索',
        'filter.statusActive': 'ACTIVE',
        'filter.statusDischarged': 'DISCHARGED',
        'filter.statusTransferred': 'TRANSFERRED',
        'table.sleep': '睡眠',
        'table.openSleepPage': '打开睡眠页面',
        'table.viewPatientDetails': '查看患者详情',
        'patientStatus.label': '患者状态',
        'patientStatus.active': '住院中',
        'patientStatus.discharged': '出院',
        'patientStatus.transferred': '转院',
        'patientStatus.updateSuccess': '状态已更新',
        'notifications.system.radar': '雷达监控系统',
        'notifications.system.status': '系统状态检查',
        'notifications.system.backup': '数据备份服务',
        'notifications.category.hr': '心率监控',
        'notifications.category.rr': '呼吸监控',
        'notifications.category.fall': '跌倒检测',
        'notifications.category.sysStatus': '系统管理/状态检查',
        'notifications.category.sysBackup': '系统管理/备份',
        'notifications.category.monitoring': '监控',
        'notifications.category.registration': '患者注册/信息生成',
        'notifications.category.emergency': '紧急通知',
        'notifications.category.warning': '警告',
        'notifications.type.hrCritical': '危急_心率',
        'notifications.type.hrWarning': '警告_心率',
        'notifications.type.hrCaution': '注意_心率',
        'notifications.type.rrCritical': '危急_呼吸',
        'notifications.type.rrWarning': '警告_呼吸',
        'notifications.type.rrCaution': '注意_呼吸',
        'notifications.type.fallDetected': '跌倒_检测',
        'notifications.type.event': '警报_事件',
        'notifications.type.sysCheck': '系统_状态_检查',
        'notifications.type.backup': '数据_备份',
        'notifications.type.patientReg': '患者_注册',
        'notifications.details.hrHigh': '心率超过危险临界值',
        'notifications.details.rrLow': '呼吸率低于安全临界值',
        'notifications.details.fallEmergency': '检测到跌倒，启动应急预案',
        'notifications.details.ack': '警报已确认',
        'notifications.details.resolved': '警报已解决',
        'notifications.details.sysNormal': '所有系统运行正常',
        'notifications.details.backupFail': '备份失败 - 连接超时',
        'notifications.details.regSuccess': '新患者注册成功',
        'monitoring.range.5m': '5分钟',
        'monitoring.range.15m': '15分钟',
        'monitoring.range.30m': '30分钟',
        'monitoring.range.1h': '1小时',
        'monitoring.range.6h': '6小时',
        'monitoring.range.24h': '24小时',
        'gps.searchPlaceholder': '通过患者姓名 / ID / 设备ID搜索...',
        'gps.noResults': '未找到搜索结果',
        'gps.autoTracking': '自动追踪',
        'gps.autoTracking.mobile': '自动追踪',
        'gps.myLocation': '显示我的位置',
        'gps.myLocation.mobile': '位置',
        'gps.errorSupport': '浏览器不支持地理定位。',
        'gps.errorFetch': '无法获取位置信息。',
        'gps.errorPermission': '地理定位权限被拒绝。请在设置中允许。',
        'gps.errorUnavailable': '位置信息不可用。',
        'gps.errorTimeout': '获取位置超时。',
        'gps.errorTracking': '实时追踪过程中发生错误。',
        'gps.userLocation': '我的位置',
        'gps.fixLocation': '固定此位置',
        'gps.assignedPatient': '负责患者',
        'gps.signalStatus': '信号状态',
        'gps.accuracy': '准确度',
        'gps.activeDevices': '活跃设备',
        'gps.uptime': '运行时间',
        'gps.horizontalPrecision': '水平精度',
        'gps.monitoring247': '24/7 监控',
        'common.relationship.spouse': '配偶',
        'common.relationship.child': '子女',
        'common.relationship.parent': '父母',
        'common.relationship.guardian': '监护人',
        'common.hospital': '国民看护医院',
        'common.warning': '警告',
        'common.noResults': '没有找到结果',
        'common.unknown': '未知',
        'status.abnormal': '异常',
        'dashboard.lastUpdated': '最后更新',
        'dashboard.usingCachedData': '正在使用缓存数据',
        'alerts.msg.hrExceeded': '心率超过临界值',
        'alerts.msg.rrOutOfRange': '呼吸率超出正常范围',
        'alerts.msg.fallDetected': '检测到跌倒',
        'alerts.msg.hrLow': '心率低于危险临界值',
        'alerts.msg.rrHigh': '呼吸率超过危险临界值',
    },
    es: {
        'dashboard.totalPatients': 'Total de Pacientes',
        'dashboard.activeAlerts': 'Alertas Activas',
        'dashboard.criticalPatients': 'Pacientes Críticos',
        'dashboard.devicesConnected': 'Dispositivos Conectados',
        'dashboard.heartRateTitle': 'Frecuencia Cardíaca',
        'dashboard.breathingRateTitle': 'Frecuencia Respiratoria',
        'dashboard.sortedByUrgency': 'Ordenado por Urgencia',
        'dashboard.heartEmergency': 'Emergencia Cardíaca',
        'dashboard.breathingEmergency': 'Emergencia Respiratoria',
        'dashboard.fallDetected': 'Caída Detectada',
        'dashboard.headerTitle': 'Panel de Monitoreo Médico',
        'dashboard.headerSubtitle': 'Sistema de Monitoreo de Pacientes',
        'sidebar.dashboard': 'Panel Principal',
        'sidebar.patientList': 'Lista de Pacientes',
        'sidebar.alertHistory': 'Historial de Alertas',
        'sidebar.sleepManagement': 'Gestión de Sueño',
        'sidebar.registration': 'Registro de Pacientes',
        'sidebar.militaryGps': 'Rastreo GPS',
        'sidebar.settings': 'Configuración',
        'sidebar.userName': 'Dr. Kim Min-jun',
        'sidebar.role': 'Administrador del Sistema',
        'sidebar.brandTitle': 'MONITOR DE RADAR',
        'sidebar.brandSubtitle': 'SISTEMA 60GHz',
        'header.systemOnline': 'En línea',
        'header.systemOffline': 'Desconectado',
        'header.exportReport': 'Exportar Informe',
        'header.liveMonitor': 'Monitor en Vivo',
        'alerts.title': 'Alertas de Emergencia',
        'alerts.description': 'Página para ver el historial de alertas pasadas.',
        'alerts.patient': 'Paciente',
        'alerts.value': 'Valor',
        'alerts.acknowledge': 'Reconocer',
        'alerts.resolve': 'Resolver',
        'alerts.currentValue': 'Actual',
        'alerts.threshold': 'Umbral',
        'alerts.viewAll': 'Ver Todo',
        'table.patientId': 'ID Paciente',
        'table.heartRate': 'Frec. Cardíaca',
        'table.breathingRate': 'Frec. Respiratoria',
        'table.sleepState': 'Estado de Sueño',
        'table.alertStatus': 'Estado de Alerta',
        'table.deviceStatus': 'Estado de Dispositivo',
        'table.lastUpdated': 'Última Actualización',
        'table.actions': 'Acciones',
        'table.viewDetails': 'Ver Detalles',
        'table.searchPlaceholder': 'Buscar por ID o Nombre...',
        'table.showing': 'Mostrando',
        'table.to': 'a',
        'table.of': 'de',
        'table.patients': 'pacientes',
        'table.filteredFrom': 'filtrado de un total de',
        'table.total': ')',
        'table.previous': 'Anterior',
        'table.next': 'Siguiente',
        'table.page': 'Página',
        'table.registrationDate': 'Fecha de Registro',
        'table.overview': 'Resumen del Paciente',
        'table.realTime': 'Monitoreo en tiempo real de todos los pacientes',
        'table.bloodType': 'Grupo Sanguíneo',
        'status.critical': 'Crítico',
        'status.warning': 'Advertencia',
        'status.caution': 'Precaución',
        'status.normal': 'Normal',
        'status.medium': 'Medio',
        'status.stable': 'Estable',
        'status.online': 'En línea',
        'status.offline': 'Desconectado',
        'status.error': 'Error',
        'status.maintenance': 'Mantenimiento',
        'status.connected': 'Conectado',
        'status.disconnected': 'Desconectado',
        'status.labelPrefix': 'Estado: ',
        'time.justNow': 'Recién',
        'time.secondsAgo': 's atrás',
        'time.minutesAgo': 'm atrás',
        'time.hour': 'h',
        'time.minute': 'm',
        'detail.back': 'Volver',
        'detail.patientInfo': 'Información del Paciente',
        'detail.gender': 'Género',
        'detail.age': 'Edad',
        'detail.room': 'Habitación',
        'detail.admissionDate': 'Fecha de Ingreso',
        'detail.admissionStatus': 'Días de Ingreso',
        'detail.diagnosis': 'Diagnóstico',
        'detail.doctor': 'Médico',
        'detail.hr': 'Frecuencia Cardíaca',
        'detail.stress': 'Índice de Estrés',
        'detail.rr': 'Frecuencia Respiratoria',
        'detail.sleepEfficiency': 'Eficiencia del Sueño',
        'detail.connection': 'Estado de Conexión',
        'detail.optimized': 'Optimizado',
        'detail.sleepAnalysis': 'Análisis de Sueño',
        'detail.hrMonitoring': 'Monitoreo de Frecuencia Cardíaca',
        'detail.rrMonitoring': 'Monitoreo de Frecuencia Respiratoria',
        'detail.detailedRecord': 'Registro Detallado',
        'detail.address': 'Dirección',
        'detail.emergencyContact': 'Contacto de Emergencia',
        'detail.allergies': 'Alergias',
        'detail.clinicalFindings': 'Hallazgos Clínicos',
        'detail.underlyingDisease': 'Enfermedad Subyacente',
        'detail.medications': 'Medicamentos',
        'detail.diet': 'Dieta',
        'detail.memo': 'Memo',
        'detail.alerts': 'Alertas de Riesgo',
        'detail.deepSleep': 'Sueño Profundo',
        'detail.lightSleep': 'Sueño Ligero',
        'detail.remSleep': 'Sueño REM',
        'detail.awake': 'Despierto',
        'detail.days': 'días',
        'detail.yearsOld': 'años',
        'detail.roomNumber': '',
        'detail.observe': 'Necesita Observación',
        'detail.none': 'Ninguno',
        'detail.checkMedication': 'Revisar prescripción',
        'detail.generalDiet': 'Dieta General',
        'detail.noSpecialMemo': 'Sin notas especiales',
        'detail.nurse': 'Enfermera',
        'detail.guardian': 'Tutor/Guardián',
        'gender.male': 'Masculino',
        'gender.female': 'Femenino',
        'gps.title': 'Rastreo GPS',
        'gps.description': 'Monitoreo de ubicación en tiempo real de los dispositivos de 60GHz conectados.',
        'registration.title': 'Registro de Información del Paciente',
        'registration.description': 'Página para registrar nuevos pacientes o equipos.',
        'registration.basicInfo': 'Información Básica',
        'registration.patientName': 'Nombre del Paciente',
        'registration.dob': 'Fecha de Nacimiento',
        'registration.gender': 'Género',
        'registration.select': 'Seleccione...',
        'registration.male': 'Masculino',
        'registration.female': 'Femenino',
        'registration.contact': 'Contacto del Paciente',
        'registration.patientNameEn': 'Nombre (EN)',
        'registration.patientCode': 'Código del Paciente',
        'registration.emergencyPhone': 'Contacto de Emergencia',
        'registration.wardId': 'ID de Pabellón',
        'registration.roomNumber': 'Número de Habitación',
        'registration.bedNumber': 'Número de Cama',
        'registration.admissionDate': 'Fecha de Ingreso',
        'registration.status': 'Estado',
        'registration.roomWard': 'Habitación',
        'registration.deviceInfo': 'Información del Dispositivo',
        'registration.deviceId': 'ID del Dispositivo',
        'registration.sensorType': 'Tipo de Sensor',
        'registration.radar60ghz': 'Radar 60GHz',
        'registration.careFacility': 'Instalación de Cuidado',
        'registration.facilityName': 'Nombre de la Instalación',
        'registration.registrationDate': 'Fecha de Registro',
        'registration.reset': 'Reiniciar',
        'registration.submit': 'Registrar',
        'registration.success': 'Información del paciente registrada.',
        'sleep.title': 'Gestión del Sueño',
        'sleep.description': 'Análisis de patrones y calidad del sueño.',
        'sleep.sessionSummary': 'Resumen de Sueño',
        'sleep.lastNight': 'Anoche',
        'sleep.totalSleep': 'SUEÑO TOTAL',
        'sleep.goal': 'Meta',
        'sleep.efficiency': 'EFICIENCIA',
        'sleep.interruptions': 'INTERRUPCIONES',
        'sleep.latency': 'LATENCIA',
        'sleep.normalRange': 'Rango Normal',
        'sleep.timesWokenUp': 'Veces que despertó',
        'sleep.timeToFallAsleep': 'Tiempo para dormir',
        'sleep.stagesDistribution': 'Distribución de etapas',
        'sleep.totalTimeInBed': 'Tiempo total en cama',
        'sleep.overallSleepScore': 'Puntuación de Sueño',
        'sleep.excellent': 'Excelente',
        'sleep.fair': 'Regular',
        'sleep.poor': 'Pobre',
        'sleep.avgComparedToUsers': 'Comparación con el promedio de su edad.',
        'sleep.hypnogram': 'Hipnograma de Sueño',
        'sleep.timeInfo': 'Info de Horarios',
        'sleep.bedIn': 'A la cama',
        'sleep.sleep': 'Dormido',
        'sleep.wakeUp': 'Despierto',
        'sleep.bedOut': 'Levantado',
        'sleep.trend': 'Tendencia de Sueño',
        'sleep.day': 'Diario',
        'sleep.weekly': 'Semanal',
        'sleep.monthly': 'Mensual',
        'sleep.vitalsCorrelation': 'Correlación de Vitales',
        'sleep.avgHr': 'FC Promedio',
        'sleep.avgResp': 'FR Promedio',
        'sleep.avgSpO2': 'SpO2 Promedio',
        'settings.title': 'Configuración',
        'settings.subtitle': 'Preferencias del Sistema',
        'settings.language': 'Idioma',
        'settings.selectLanguage': 'Seleccionar idioma',
        'settings.description': 'Configurar preferencias del entorno.',
        'settings.langUpdateNote': 'Cambiar el idioma actualizará toda la interfaz de la aplicación al idioma seleccionado.',
        'common.save': 'Guardar',
        'common.cancel': 'Cancelar',
        'common.today': 'Hoy',
        'common.reset': 'Reiniciar',
        'common.collapse': 'Contraer',
        'common.bpm': 'BPM',
        'common.rpm': 'RPM',
        'error.loadingData': 'Error al cargar los datos.',
        'error.patientNotFound': 'Paciente no encontrado.',
        'notifications.table.date': 'Fecha',
        'notifications.table.system': 'Sistema',
        'notifications.table.patientId': 'ID Paciente',
        'notifications.table.category': 'Categoría',
        'notifications.table.type': 'Tipo',
        'notifications.table.status': 'Estado',
        'notifications.table.details': 'Detalles',
        'notifications.table.noLogs': 'No hay registros para mostrar.',
        'notifications.table.success': 'Éxito',
        'notifications.table.fail': 'Fallo',
        'notifications.history': 'Historial de Notificaciones',
        'notifications.logs': 'Registros de Notificaciones',
        'filter.allStatus': 'Todos los Estados',
        'filter.active': 'Activo',
        'filter.active.mobile': 'Activo',
        'filter.discharged': 'Dado de Alta',
        'filter.discharged.mobile': 'Alta',
        'filter.transferred': 'Transferido',
        'filter.transferred.mobile': 'Transf.',
        'filter.searchPlaceholder': 'Buscar por nombre o ID',
        'filter.statusActive': 'ACTIVE',
        'filter.statusDischarged': 'DISCHARGED',
        'filter.statusTransferred': 'TRANSFERRED',
        'table.sleep': 'Sueño',
        'table.openSleepPage': 'Abrir Página de Sueño',
        'table.viewPatientDetails': 'Ver Detalles del Paciente',
        'patientStatus.label': 'Estado del Paciente',
        'patientStatus.active': 'Hospitalizado',
        'patientStatus.discharged': 'Dado de Alta',
        'patientStatus.transferred': 'Transferido',
        'patientStatus.updateSuccess': 'Estado actualizado correctamente',
        'notifications.system.radar': 'Sistema de Monitoreo por Radar',
        'notifications.system.status': 'Verificación de Estado del Sistema',
        'notifications.system.backup': 'Servicio de Respaldo de Datos',
        'notifications.category.hr': 'Monitoreo de Frecuencia Cardíaca',
        'notifications.category.rr': 'Monitoreo de Respiración',
        'notifications.category.fall': 'Detección de Caídas',
        'notifications.category.sysStatus': 'Gestión/Estado del Sistema',
        'notifications.category.sysBackup': 'Gestión/Respaldo del Sistema',
        'notifications.category.monitoring': 'Monitoreo',
        'notifications.category.registration': 'Registro/Información de Paciente',
        'notifications.category.emergency': 'Alerta de Emergencia',
        'notifications.category.warning': 'Advertencia',
        'notifications.type.hrCritical': 'FC_CRÍTICA',
        'notifications.type.hrWarning': 'FC_ADVERTENCIA',
        'notifications.type.hrCaution': 'FC_PRECAUCIÓN',
        'notifications.type.rrCritical': 'FR_CRÍTICA',
        'notifications.type.rrWarning': 'FR_ADVERTENCIA',
        'notifications.type.rrCaution': 'FR_PRECAUCIÓN',
        'notifications.type.fallDetected': 'CAÍDA_DETECTADA',
        'notifications.type.event': 'EVENTO_DE_ALERTA',
        'notifications.type.sysCheck': 'CHEQUEO_DEL_SISTEMA',
        'notifications.type.backup': 'RESPALDO_DE_DATOS',
        'notifications.type.patientReg': 'REGISTRO_DE_PACIENTE',
        'notifications.details.hrHigh': 'La frecuencia cardíaca superó el umbral de peligro',
        'notifications.details.rrLow': 'La frecuencia respiratoria está por debajo del umbral de seguridad',
        'notifications.details.fallEmergency': 'Caída detectada, iniciando protocolo de emergencia',
        'notifications.details.ack': 'Alerta reconocida',
        'notifications.details.resolved': 'Alerta resuelta',
        'notifications.details.sysNormal': 'Todos los sistemas funcionan normalmente',
        'notifications.details.backupFail': 'Fallo en respaldo - Tiempo de espera agotado',
        'notifications.details.regSuccess': 'Nuevo paciente registrado con éxito',
        'monitoring.range.5m': '5m',
        'monitoring.range.15m': '15m',
        'monitoring.range.30m': '30m',
        'monitoring.range.1h': '1h',
        'monitoring.range.6h': '6h',
        'monitoring.range.24h': '24h',
        'gps.searchPlaceholder': 'Buscar paciente / ID / Dispositivo...',
        'gps.noResults': 'No se encontraron resultados',
        'gps.autoTracking': 'Rastreo Automático',
        'gps.autoTracking.mobile': 'Rastreo Auto',
        'gps.myLocation': 'Mostrar mi Ubicación',
        'gps.myLocation.mobile': 'Ubicación',
        'gps.errorSupport': 'El navegador no soporta geolocalización.',
        'gps.errorFetch': 'No se pudo obtener la ubicación.',
        'gps.errorPermission': 'Permiso de ubicación denegado. Permítalo en ajustes.',
        'gps.errorUnavailable': 'Información de ubicación no disponible.',
        'gps.errorTimeout': 'La solicitud de ubicación expiró.',
        'gps.errorTracking': 'Ocurrió un error en el rastreo en tiempo real.',
        'gps.userLocation': 'Mi Ubicación',
        'gps.fixLocation': 'Fijar esta ubicación',
        'gps.assignedPatient': 'Paciente Asignado',
        'gps.signalStatus': 'Estado de Señal',
        'gps.accuracy': 'Precisión',
        'gps.activeDevices': 'Dispositivos Activos',
        'gps.uptime': 'Tiempo de Actividad',
        'gps.horizontalPrecision': 'Precisión horizontal',
        'gps.monitoring247': 'Monitoreo 24/7',
        'common.relationship.spouse': 'Cónyuge',
        'common.relationship.child': 'Hijo/a',
        'common.relationship.parent': 'Padre/Madre',
        'common.relationship.guardian': 'Tutor/Guardián',
        'common.hospital': 'Hospital Nacional de Enfermería',
        'common.warning': 'Advertencia',
        'common.noResults': 'No se encontraron resultados',
        'common.unknown': 'Desconocido',
        'status.abnormal': 'Anormal',
        'dashboard.lastUpdated': 'Última actualización',
        'dashboard.usingCachedData': 'Usando datos en caché',
        'alerts.msg.hrExceeded': 'La frecuencia cardíaca excedió el umbral',
        'alerts.msg.rrOutOfRange': 'La frecuencia respiratoria está fuera del rango normal',
        'alerts.msg.fallDetected': 'Se detectó una caída',
        'alerts.msg.hrLow': 'Frecuencia cardíaca por debajo del umbral peligroso',
        'alerts.msg.rrHigh': 'Frecuencia respiratoria excedió el umbral peligroso',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'medical-radar-language';

export function LanguageProvider({ children }: { children: ReactNode }) {
    // Initialize language from localStorage or default to 'ko'
    const [language, setLanguageState] = useState<Language>(() => {
        if (typeof window !== 'undefined') {
            const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language;
            if (saved && ['ko', 'en', 'ja', 'ch', 'es'].includes(saved)) {
                return saved;
            }
        }
        return 'ko';
    });

    // Persist language to localStorage when changed
    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        if (typeof window !== 'undefined') {
            localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
        }
    };

    // Sync language from localStorage on mount (for SSR compatibility)
    useEffect(() => {
        const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language;
        if (saved && ['ko', 'en', 'ja', 'ch', 'es'].includes(saved) && saved !== language) {
            setLanguageState(saved);
        }
    }, []);

    /**
     * Translate a key using the current language.
     * Fallback order: selected language → English → key itself
     */
    const t = (key: string): string => {
        const currentTranslations = translations[language];
        const englishTranslations = translations['en'];
        return currentTranslations?.[key] || englishTranslations?.[key] || key;
    };

    /**
     * Get localized text from an API data object with multiple language versions.
     * Handles objects like { ko: "한국어", en: "English", ja: "日本語", ch: "中文", es: "Español" }
     * Also handles plain strings and null/undefined values.
     * 
     * @param data - The multilingual data object or plain string
     * @param fallback - Optional fallback value if no translation is found
     * @returns The localized string for the current language
     */
    const getLocalizedText = (
        data: Record<string, string> | string | undefined | null,
        fallback: string = ''
    ): string => {
        // If data is null or undefined, return fallback
        if (data === null || data === undefined) {
            return fallback;
        }

        // If data is already a string, return it directly
        if (typeof data === 'string') {
            return data;
        }

        // If data is an object, try to get the value for current language
        // Fallback order: current language → English → Korean → first available → fallback
        return (
            data[language] ||
            data['en'] ||
            data['ko'] ||
            Object.values(data)[0] ||
            fallback
        );
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, getLocalizedText }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
